<?php 

		
	/*********************
	*   estateView
	*********************/
	
	
	// estateView setting
	(!empty(get_option('ff-estateView-template')))? define('EW_ESTATEVIEW_THEME', get_option('ff-estateView-template') ) : define('EW_ESTATEVIEW_THEME', 'default' ) ;
	(!empty(get_option('ff-estateView-publish')))? define('FF_ESTATEVIEW_PUBLISH', get_option('ff-estateView-publish') ) : define('FF_ESTATEVIEW_PUBLISH', '8e2cd4a3-c462-470c-9c0f-e38797dfdb4b' ) ;	

	//seo setting
	(!empty(get_option('ff-estateView-seo-slug')))? define('FF_ESTATEVIEW_SEO_SLUG', get_option('ff-estateView-seo-slug') ) : define('FF_ESTATEVIEW_SEO_SLUG', '' ) ;
	(!empty(get_option('ff-estateView-seo')))? define('FF_ESTATEVIEW_SEO', get_option('ff-estateView-seo') ) : define('FF_ESTATEVIEW_SEO', 'on' ) ;
	define('FF_ESTATEVIEW_SEO_SITEMAP', get_home_url().'/'.EW_PLUGIN_ROUTE.'/'.FF_ESTATEVIEW_ROUTE );
	
	// estatereference search setting
	(!empty(get_option('ff-estateView-max-result')))? define('FF_ESTATEVIEW_MAX_RESULT', get_option('ff-estateView-max-result') ) : define('FF_ESTATEVIEW_MAX_RESULT', 15 ) ;
	
	// allow estate sharing to socialmedia
	(!empty(get_option('ff-estateView-show-socialmedia-links')))? define('FF_ESTATEVIEW_SHOW_SOCIALMEDIA_LINKS', get_option('ff-estateView-show-socialmedia-links') ) : define('FF_ESTATEVIEW_SHOW_SOCIALMEDIA_LINKS', 0 ) ;
	
	// estateView salesautomat setting
	$mapping = '{
		"schema":{
			"default":{
				"caption":	"Alle",
				"varity":	""
			},
			"house_purchase": {
				"caption":	"Haus",
				"varity":	"purchase"
			},
			"houses_rent": {
				"caption":	"Haus",
				"varity":	"rent"
			},
			"flat_purchase": {
				"caption":	"Wohnung",
				"varity":	"purchase"
			},
			"flat_rent": {
				"caption":	"Wohnung",
				"varity":	"rent"
			},
			"temporary_accommodation": {
				"caption":	"Wohnen auf Zeit",
				"varity":	"rent"
			},
			"land_purchase": {
				"caption":	"Grundstück",
				"varity":	"purchase"
			},
			"land_lease": {
				"caption":	"Grundstück",
				"varity":	"rent"
			},
			"office_surgery_purchase": {
				"caption":	"Büro / Praxis",
				"varity":	"purchase"
			},
			"office_surgery_rent": {
				"caption":	"Büro / Praxis",
				"varity":	"rent"
			},
			"shops_commerce_purchase": {
				"caption":	"Einzelhandel",
				"varity":	"purchase"
			},
			"shops_commerce_rent": {
				"caption":	"Einzelhandel",
				"varity":	"rent"
			},
			"catering_accommodation_purchase": {
				"caption":	"Gastronomie / Beherbergung",
				"varity":	"purchase"
			},
			"catering_accommodation_rent": {
				"caption":	"Gastronomie / Beherbergung",
				"varity":	"rent"
			},
			"investment": {
				"caption":	"Investment",
				"varity":	"purchase"
			},
			"production_halls_purchase": {
				"caption":	"Produktion / Hallen",
				"varity":	"purchase"
			},
			"production_halls_rent": {
				"caption":	"Produktion / Hallen",
				"varity":	"rent"
			},
			"agriculture_and_forestry_purchase": {
				"caption":	"Land-/Forstwirtschaftliche Flächen",
				"varity":	"purchase"
			}
		},
		"search":{},
		"seo": {
			"default": {
				"data": {
					"estatetype": {
						"caption": "Immobilienart",
						"type": "option",
						"unit": "",
						"option": {
							"15EM": "Ein/Mehrfamilienhaus (ZV)",
							"16EM": "EinfamilienhausMitEinliegerwohnung (Typ)",
							"15GE": "Gewerbe/Anlage (ZV)",
							"16HO": "Holzhaus (Typ)",
							"14LO": "Loft (WG)",
							"14TE": "Terrassenwohnung (WG)",
							"16": "Typenhäuser (Typ)",
							"02REND": "Reihenendhaus",
							"02ZSTAD": "Stadthaus",
							"02ZREST": "Resthof",
							"02ZLAND": "Landhaus",
							"02ZBERG": "Berghütte",
							"02ZCHAL": "Chalet",
							"02ZSTRA": "Strandhaus",
							"02ZLAUB": "Laube/Datsche/Gartenhaus",
							"02ZAPAH": "Apartmenthaus",
							"02ZHERR": "Herrenhaus",
							"02ZFINC": "Finca",
							"02ZRUST": "Rustico",
							"02ZFERT": "Fertighaus",
							"03INDU": "Baugrund für Industrie",
							"03GEMI": "Gemischte Nutzung",
							"03GEWE": "Gewerbepark",
							"03SOND": "Sondernutzung",
							"03SEEL": "Seeliegenschaft",
							"05EINHA": "Einzelhandelsladen",
							"05VERBR": "Verbrauchermarkt",
							"01ZAPART": "Apartment",
							"01ZFERIE": "Ferienwohnung",
							"01ZGALER": "Galerie",
							"08GASTW": "Gastronomie mit Wohnung",
							"08BEHERB": "Weitere Beherbergungsbetriebe",
							"08RAUCH": "Raucherlokal",
							"08EINRA": "Einraumlokal",
							"07PROD": "Produktion",
							"07FREIF": "Freiflächen",
							"09AUSS": "Aussiedlerhof",
							"09GART": "Gartenbau",
							"09ACKE": "Ackerbau",
							"09VIEH": "Viehwirtschaft",
							"09JAGD": "Jagd- u. Forstwirtschaft",
							"09TEICH": "Teich- u. Fischwirtschaft",
							"09SCHEU": "Scheunen",
							"09SONST": "Sonstige Landwirtschaftsimmobilien",
							"09JAGDR": "Jagdrevier",
							"11DOPP": "Doppelgarage",
							"11BOOT": "Bootsliegeplatz",
							"11EINZE": "Einzelgarage",
							"11STROM": "Parkplatz-Strom",
							"04VERB": "Verbrauchermärkte (Invest)",
							"04PFLEG": "Pflegeheim (Invest)",
							"04SANAT": "Sanatorium (Invest)",
							"04SENIO": "Seniorenheim (Invest)",
							"04CBETRE": "Betreutes Wohnen (Invest)",
							"20": "Freizeitimmobilien gewerblich",
							"20SPORT": "Sportanlagen",
							"20VERGN": "Vergnügungspark/-Center",
							"21": "Sonstige Typen",
							"21PARKH": "Parkhaus",
							"21TANKS": "Tankstelle",
							"21KRANK": "Krankenhaus",
							"21SONST": "Sonstige",
							"15GR": "Grundstück (ZV)",
							"02SON": "sonstige Häuser",
							"01LOFT": "Loftwohnung",
							"02MFH": "Mehrfamilienhaus",
							"08HOTG": "Hotel garni",
							"01ETAG": "Etagenwohnung",
							"02DZH": "Zweifamilienhaus",
							"07LKÜ": "Kühlhaus",
							"03BE": "Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR": "Kühlregallager",
							"08GAHS": "Gästehaus",
							"07LFR": "Lager mit Freifläche",
							"07L": "Lagerfläche",
							"01ZO": "sonstiger Wohnungstyp",
							"08": "Gastronomie / Beherbergungen",
							"06A1": "Loft",
							"06": "Büro / Praxis / Ausstellungsräume",
							"04W03": "Mehrfamilienhaus (Invest.)",
							"07LH": "Lagerhalle",
							"04": "Anlage-/Investmentobjekte",
							"07SF": "Servicefläche",
							"07LSP": "Speditionslager",
							"07W": "Werkstatt",
							"02ZB": "besondere Immobilie",
							"09R": "Reiterhof",
							"01MAIS": "Maisonettewohnung",
							"03GL": "Grundstück Land und Forstwirtschaft",
							"03": "Grundstücke",
							"10GE": "Gewerbeeinheit",
							"10S": "Spezialobjekt",
							"02LBH": "Bauernhaus",
							"03GG": "Baugrund für Gewerbe",
							"08HOT": "Hotel",
							"06A": "Atelier",
							"09": "Land- / Forstwirtschaft",
							"02": "Haus",
							"04W04": "Wohnanlage (Invest.)",
							"07": "Prod./ Lager / Gewerbehallen",
							"08GAE": "Gaststätte",
							"04W02": "Einfamilienhaus (Invest.)",
							"01PENT": "Penthouse",
							"02EFH": "Einfamilienhaus",
							"04W01": "Eigentumswohnung (Invest.)",
							"02REH": "Reihenhaus",
							"04EZ": "Einkaufszentrum (Invest.)",
							"03GF": "Baugrund für Freizeit",
							"02VIL": "Villa",
							"04GA": "Gaststätte (Invest.)",
							"06B": "Büro",
							"04K": "Freizeitanlage (Invest.)",
							"08REST": "Restaurant",
							"01": "Wohnung",
							"08PENS": "Pension",
							"01DACH": "Dachgeschosswohnung",
							"04W05": "Wohn-/Geschäftshaus (Invest.)",
							"05": "Läden/SB-Märkte",
							"02DHH": "Doppelhaushälfte",
							"06BE": "Büroetage",
							"10": "Sonstige Immobilie",
							"07H": "Halle",
							"01TERR": "Terrassenwohnung",
							"01GERD": "Erdgeschosswohnung",
							"06PH": "Praxishaus",
							"06G": "Gewerbezentrum",
							"05F": "Verkaufshalle",
							"08B": "Bar",
							"07LHO": "Hochregallager",
							"07HI": "Industriehalle",
							"07HIF": "Industriehalle mit Freifläche",
							"10F": "Freizeitanlage",
							"10G": "Gewerbefläche",
							"06BH": "Bürohaus",
							"06BG": "Bürozentrum",
							"06BL": "Büro & Lagergebäude",
							"06P": "Praxis",
							"06PE": "Praxisetage",
							"05A": "Ausstellungsfläche",
							"05E1": "Einkaufszentrum",
							"05E2": "Kaufhaus",
							"05K": "Kiosk",
							"05L": "Laden",
							"11C": "Carport",
							"02REHM": "Reihenmittelhaus",
							"10W": "Werkstatt (Produktion)",
							"14DA": "Dachgeschoss (WG)",
							"16FA": "Fachwerkhaus (Typ)",
							"14MA": "Maisonette (WG)",
							"14PE": "Penthouse (WG)",
							"16DO": "Doppelhaus (Typ)",
							"15GA": "Garage/Sonstige (ZV)",
							"14SU": "Souterrain (WG)",
							"01ZROHD": "Rohdachboden (AUT)",
							"01ZATTIK": "Attikawohnung",
							"05E": "SB-Markt",
							"05LV": "Verkaufsfläche",
							"08C": "Cafe",
							"08D": "Diskothek",
							"08HOTA": "Hotelanwesen",
							"09A1": "Anwesen",
							"09A2": "Bauernhof",
							"09W": "Weingut",
							"04GWE": "Gewerbeeinheit (Invest.)",
							"04EG": "Geschäftshaus (Invest.)",
							"04GH": "Halle/Lager (Invest.)",
							"04E": "Laden/Verkaufsfläche (Invest.)",
							"04ES": "Supermarkt (Invest.)",
							"04B": "Bürogebäude (Invest.)",
							"04GWA": "Gewerbeanwesen (Invest.)",
							"04S": "Servicecenter (Invest.)",
							"04Z": "Sonstiges (Invest.)",
							"04GAH": "Hotel (Invest.)",
							"04GWI": "Industrieanwesen (Invest.)",
							"15EI": "Eigentumswohnung (ZV)",
							"16EI": "Einfamilienhaus (Typ)",
							"16LA": "Landhaus (Typ)",
							"14SO": "Sonstige (WG)",
							"16SV": "Stadtvilla (Typ)",
							"14": "WG-Zimmer (WG)",
							"15": "Zwangsversteigerung (ZV)",
							"16ZW": "Zweifamilienhaus (Typ)",
							"12A": "Appartement",
							"08F": "Ferienbungalows",
							"02EFE": "Einfamilienhaus mit Einliegerwohnung",
							"11G": "Garage",
							"11T": "Tiefgaragenstellplatz",
							"10GP": "Gewerbepark",
							"12H": "Haus",
							"12W": "Wohnung (WAZ)",
							"12Z": "Zimmer (WAZ)",
							"12": "Wohnen auf Zeit (WAZ)",
							"16BL": "Blockhaus (Typ)",
							"11S": "Stellplatz",
							"07A": "Ausstellungsfläche (Produktion)",
							"02BNG": "Bungalow",
							"02BURG": "Burg/Schloss",
							"06BUGE": "Büro- u. Geschäftsgebäude",
							"11D": "Duplex",
							"11": "Garage Stellplatz",
							"01HP": "Hochparterre",
							"11P": "Parkhausstellplatz",
							"02REHE": "Reiheneckhaus",
							"01SOUT": "Souterrain",
							"06WOGE": "Wohn- u. Geschäftsgebäude",
							"14ER": "Erdgeschoss (WG)",
							"08Beher": "Beherbergungsbetrieb",
							"03indust": "Baugrundstück für Wohnungen und Industrie",
							"03dup": "Baugrundstück für freistehende und Duplexhäuser",
							"03BM": "Baugrund für Mehrfamilienhäuser",
							"03BWG": "Baugrund für Wohnen und Gewerbe",
							"03GS": "Grundstück für Soziales",
							"04GW": "Industrie- und Gewerbeimmobilien (Invest.)",
							"04HI": "Handelsimmobilien (Invest.)",
							"04HIF": "Fachmarktzentrum (Invest.)",
							"04HIK": "Kaufhaus (Invest.)",
							"04SI": "Sozialimmobilien (Invest.)",
							"04SIB": "Betreutes Wohnen (Invest.)",
							"04SIP": "Pflegeheim (Invest.)",
							"04SIK": "Klinik (Invest.)",
							"04W": "Wohnimmobilien (Invest.)",
							"04ZP": "Parkhaus (Invest.)",
							"09F": "Fischzucht",
							"08PENT": "Boardinghaus",
							"11Z": "Sonstiges",
							"01LOFT": "Loftwohnung",
							"08HOTG": "Hotel garni",
							"01ETAG": "Etagenwohnung",
							"02DZH": "Zweifamilienhaus",
							"07LKÜ": "Kühlhaus",
							"03BE": "Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR": "Kühlregallager",
							"08GAHS": "Gästehaus",
							"07LFR": "Lager mit Freifläche",
							"07L": "Lagerfläche",
							"01ZO": "Sonstiger Wohnungstyp",
							"08": "Hotellerie- und Gastronomieflächen",
							"06A1": "Loft",
							"06": "Gewerbeflächen",
							"04W03": "Mehrfamilienhaus (Invest.)",
							"07LH": "Lagerhalle",
							"04": "Anlage-/Investmentobjekte",
							"07SF": "Servicefläche",
							"07LSP": "Speditionslager",
							"07W": "Werkstattsfläche",
							"02ZB": "Besondere Immobilie",
							"09R": "Reiterhof",
							"01MAIS": "Maisonettewohnung",
							"03GL": "Grundstück Land und Forstwirtschaft",
							"03": "Grundstücke",
							"10GE": "Gewerbeeinheit",
							"10S": "Spezialobjekt",
							"02LBH": "Bauernhaus",
							"03GG": "Baugrund für Gewerbe",
							"08HOT": "Hotel",
							"06A": "Atelier",
							"09": "Land- / Forstwirtschaft",
							"02": "Haus",
							"04W04": "Wohnanlage (Invest.)",
							"07": "Produktions- und Lagerflächen",
							"08GAE": "Gaststätte",
							"04W02": "Einfamilienhaus (Invest.)",
							"01PENT": "Penthouse",
							"02EFH": "Einfamilienhaus",
							"04W01": "Eigentumswohnung (Invest.)",
							"02REH": "Reihenhaus",
							"04HIE": "Einkaufszentrum (Invest.)",
							"03GF": "Baugrund für Freizeit",
							"02MFH": "Mehrfamilienhaus",
							"02EFE": "Einfamilienhaus mit Einliegerwohnung",
							"11G": "Garage",
							"11T": "Tiefgaragenstellplatz",
							"11S": "Stellplatz",
							"12A": "Apartment",
							"08F": "Ferienimmobilie",
							"10GP": "Gewerbepark",
							"12H": "Haus",
							"12W": "Wohnung",
							"12Z": "Zimmer",
							"07A": "Ausstellungsfläche (Produktion)",
							"02BNG": "Bungalow",
							"06BUGE": "Büro- und Geschäftsgebäude",
							"11C": "Carport",
							"11D": "Duplex",
							"11": "Garage Stellplatz",
							"01HP": "Hochparterre",
							"11P": "Parkhausstellplatz",
							"02REHM": "Reihenmittelhaus",
							"01SOUT": "Souterrain",
							"06WOGE": "Wohn- und Geschäftsgebäude",
							"02REHE": "Reiheneckhaus",
							"10W": "Werkstatt (Produktion)",
							"02VIL": "Villa",
							"04GA": "Gaststätte / Gasthaus (Invest.)",
							"06B": "Bürofläche",
							"04ZF": "Freizeitimmobilie (Invest.)",
							"08REST": "Restaurant",
							"01": "Wohnung",
							"08PENS": "Pension",
							"01DACH": "Dachgeschosswohnung",
							"04W05": "Wohn-/Geschäftshaus (Invest.)",
							"05": "Einzelhandelsflächen",
							"02DHH": "Doppelhaushälfte",
							"06BE": "Büroetage",
							"10": "Sonstige Objekte",
							"07H": "Halle",
							"01TERR": "Terrassenwohnung",
							"01GERD": "Erdgeschosswohnung",
							"06PH": "Praxishaus",
							"06G": "Gewerbezentrum",
							"05F": "Verkaufshalle",
							"08B": "Bar",
							"07LHO": "Hochregallager",
							"07HI": "Produktionsfläche",
							"07HIF": "Industriehalle mit Freifläche",
							"10F": "Freizeitanlage",
							"10G": "Gewerbefläche",
							"06BH": "Bürohaus",
							"06BG": "Bürozentrum",
							"06BL": "Büro und Lagergebäude",
							"06P": "Praxis",
							"06PE": "Praxisfläche",
							"05A": "Ausstellungsfläche",
							"05E1": "Einkaufszentrum",
							"05F1": "Factory Outlet",
							"05E2": "Kaufhaus",
							"05K": "Kiosk",
							"05L": "Laden",
							"05E": "SB-Markt",
							"05LV": "Verkaufsfläche",
							"08C": "Cafe",
							"08D": "Diskothek",
							"08HOTA": "Hotelanwesen",
							"09A1": "Anwesen",
							"09A2": "Bauernhof",
							"09W": "Weingut",
							"04GWE": "Gewerbeeinheit (Invest.)",
							"04GWG": "Geschäftshaus, Handel, Büro (Invest.)",
							"04GWH": "Halle/Lager (Invest.)",
							"04HIL": "Laden/Verkaufsfläche (Invest.)",
							"04HIS": "Supermarkt (Invest.)",
							"04GWB": "Bürogebäude (Invest.)",
							"04GWA": "Gewerbeanwesen (Invest.)",
							"04GWS": "Servicecenter (Invest.)",
							"04Z": "Sonstiges (Invest.)",
							"04GAH": "Hotel (Invest.)",
							"04GWI": "Industrieanwesen (Invest.)",
							"02BURG": "Burg/Schloss",
							"02SON": "Sonstige Häuser",
							"12": "Wohnen auf Zeit"
						}
					},	
					"headline": {
						"caption": "headline",
						"type": "text",
						"unit": ""
					},
					"identifier": {
						"caption": "Immobilien-ID",
						"type": "text",
						"unit": ""
					},
					"livingSpace": {
						"caption": "Wohnfläche",
						"type": "area",
						"unit": "m²"
					},
					"commercialarea": {
						"caption": "Gewerbefläche",
						"type": "area",
						"unit": "m²"
					},
					"numbersOfRooms": {
						"caption": "Zimmer",
						"type": "number",
						"unit": ""
					},
					"plotArea": {
						"caption": "Grundstück",
						"type": "area",
						"unit": "m²"
					},
					"gastroarea": {
						"caption": "Gastronomiefläche",
						"type": "number",
						"unit": "m²"
					},
					"totalFloorSpace": {
						"caption": "Gesamtfläche",
						"type": "area",
						"unit": "m²"
					},
					"numberbeds": {
						"caption": "Anzahl Betten",
						"type": "number",
						"unit": ""
					},
					"development": {
						"caption": "Erschließung",
						"type": "option",
						"unit": "",
						"option": {
							"TE": "Teilweise erschlossen",
							"VE": "Voll erschlossen",
							"NE": "Nicht erschlossen"
						}
					},
					"availableat": {
						"caption": "Verfügbar ab",
						"type": "date",
						"unit": ""
					}
				}
			}
		},
		"sort":{
			"default": {
				"date": {
					"caption":	"Aktuellste zuerst",
					"selected":	false,
					"fields":[
						{
							"sort":"DESC",
							"field":"_metadata.lastModifiedTimestamp"
						}
					]	
				},
				"price": {
					"caption":	"Preis aufsteigend",
					"selected":	false,
					"fields":[
						{
							"sort":	"ASC",
							"field":"rent"
						},
						{
							"sort":	"ASC",
							"field":"purchaseprice"
						}
					]	
					
				},
				"price_up": {
					"caption":	"Preis absteigend",
					"selected":	false,
					"fields":[
						{
							"sort":	"DESC",
							"field":"purchaseprice"
						},
						{
							"sort":	"DESC",
							"field":"rent"
						}
					]	
					
				}
			}
		},
		"list":	{
			"default":{
				"id": {
					"caption":	"id",
					"type":		"id",
					"unit":		""
				},
				"metadata": {
					"_metadata": {
						"caption":	"metadata",
						"type":		"metadata",
						"unit":		""
					}
				},
				"headline":{
					"headline": {
						"caption": "headline",
						"type": "text",
						"unit": ""
					}			
				},			
				"mainImage":{
					"mainImage": {
						"caption":	"Titlebild",
						"type":		"image",
						"unit":		""
					}
				},
				"details":{
					"identifier": {
						"caption":	"Immobilien-ID",
						"type":		"text",
						"unit":		""
					},
					"livingSpace": {
						"caption":	"Wohnfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"commercialarea": {
						"caption":	"Gewerbefläche",
						"type":		"area",
						"unit":		"m²"
					},
					"numbersOfRooms": {
						"caption":	"Zimmer",
						"type":		"number",
						"unit":		""
					},
					"plotArea": {
						"caption":	"Grundstück",
						"type":		"area",
						"unit":		"m²"
					},
					"gastroarea": {
						"caption":	"Gastronomiefläche",
						"type":		"number",
						"unit":		"m²"
					},
					"totalFloorSpace": {
						"caption":	"Gesamtfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"plotAreainha": {
						"caption":	"Grundstücksfläche",
						"type":		"area",
						"unit":		"ha"
					},
					"agriculturearea": {
						"caption":	"Landwirt. Fläche",
						"type":		"number",
						"unit":		"ha"
					},
					"forestryarea": {
						"caption":	"Forstwirt. Fläche",
						"type":		"number",
						"unit":		"ha"
					},
					"numberbeds": {
						"caption":	"Anzahl Betten",
						"type":		"number",
						"unit":		""
					},
					"development": {
						"caption":	"Erschließung",
						"type":		"option",
						"unit":		"",
						"option": {
							"TE":"Teilweise erschlossen",
							"VE":"Voll erschlossen",
							"NE":"Nicht erschlossen"
						}
					},					
					"availableat": {
						"caption":	"Verfügbar ab",
						"type":		"date",
						"unit":		""
					},
					"_metadata": {
						"_metadata": {
							"caption":	"metadata",
							"type":		"metadata",
							"unit":		""
						}
					}
				},
				"estatetype":{
					"estatetype": {
						"caption":	"Immobilienart",
						"type":		"option",
						"unit":		"",
						"option":	{
							"15EM":"Ein/Mehrfamilienhaus (ZV)",
							"16EM":"EinfamilienhausMitEinliegerwohnung (Typ)",
							"15GE":"Gewerbe/Anlage (ZV)",
							"16HO":"Holzhaus (Typ)",
							"14LO":"Loft (WG)",
							"14TE":"Terrassenwohnung (WG)",
							"16":"Typenhäuser (Typ)",
							"02REND":"Reihenendhaus",
							"02ZSTAD":"Stadthaus",
							"02ZREST":"Resthof",
							"02ZLAND":"Landhaus",
							"02ZBERG":"Berghütte",
							"02ZCHAL":"Chalet",
							"02ZSTRA":"Strandhaus",
							"02ZLAUB":"Laube/Datsche/Gartenhaus",
							"02ZAPAH":"Apartmenthaus",
							"02ZHERR":"Herrenhaus",
							"02ZFINC":"Finca",
							"02ZRUST":"Rustico",
							"02ZFERT":"Fertighaus",
							"03INDU":"Baugrund für Industrie",
							"03GEMI":"Gemischte Nutzung",
							"03GEWE":"Gewerbepark",
							"03SOND":"Sondernutzung",
							"03SEEL":"Seeliegenschaft",
							"05EINHA":"Einzelhandelsladen",
							"05VERBR":"Verbrauchermarkt",
							"01ZAPART":"Apartment",
							"01ZFERIE":"Ferienwohnung",
							"01ZGALER":"Galerie",
							"08GASTW":"Gastronomie mit Wohnung",
							"08BEHERB":"Weitere Beherbergungsbetriebe",
							"08RAUCH":"Raucherlokal",
							"08EINRA":"Einraumlokal",
							"07PROD":"Produktion",
							"07FREIF":"Freiflächen",
							"09AUSS":"Aussiedlerhof",
							"09GART":"Gartenbau",
							"09ACKE":"Ackerbau",
							"09VIEH":"Viehwirtschaft",
							"09JAGD":"Jagd- u. Forstwirtschaft",
							"09TEICH":"Teich- u. Fischwirtschaft",
							"09SCHEU":"Scheunen",
							"09SONST":"Sonstige Landwirtschaftsimmobilien",
							"09JAGDR":"Jagdrevier",
							"11DOPP":"Doppelgarage",
							"11BOOT":"Bootsliegeplatz",
							"11EINZE":"Einzelgarage",
							"11STROM":"Parkplatz-Strom",
							"04VERB":"Verbrauchermärkte (Invest)",
							"04PFLEG":"Pflegeheim (Invest)",
							"04SANAT":"Sanatorium (Invest)",
							"04SENIO":"Seniorenheim (Invest)",
							"04CBETRE":"Betreutes Wohnen (Invest)",
							"20":"Freizeitimmobilien gewerblich",
							"20SPORT":"Sportanlagen",
							"20VERGN":"Vergnügungspark/-Center",
							"21":"Sonstige Typen",
							"21PARKH":"Parkhaus",
							"21TANKS":"Tankstelle",
							"21KRANK":"Krankenhaus",
							"21SONST":"Sonstige",
							"15GR":"Grundstück (ZV)",
							"02SON":"sonstige Häuser",
							"01LOFT":"Loftwohnung",
							"02MFH":"Mehrfamilienhaus",
							"08HOTG":"Hotel garni",
							"01ETAG":"Etagenwohnung",
							"02DZH":"Zweifamilienhaus",
							"07LKÜ":"Kühlhaus",
							"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR":"Kühlregallager",
							"08GAHS":"Gästehaus",
							"07LFR":"Lager mit Freifläche",
							"07L":"Lagerfläche",
							"01ZO":"sonstiger Wohnungstyp",
							"08":"Gastronomie / Beherbergungen",
							"06A1":"Loft",
							"06":"Büro / Praxis / Ausstellungsräume",
							"04W03":"Mehrfamilienhaus (Invest.)",
							"07LH":"Lagerhalle",
							"04":"Anlage-/Investmentobjekte",
							"07SF":"Servicefläche",
							"07LSP":"Speditionslager",
							"07W":"Werkstatt",
							"02ZB":"besondere Immobilie",
							"09R":"Reiterhof",
							"01MAIS":"Maisonettewohnung",
							"03GL":"Grundstück Land und Forstwirtschaft",
							"03":"Grundstücke",
							"10GE":"Gewerbeeinheit",
							"10S":"Spezialobjekt",
							"02LBH":"Bauernhaus",
							"03GG":"Baugrund für Gewerbe",
							"08HOT":"Hotel",
							"06A":"Atelier",
							"09":"Land- / Forstwirtschaft",
							"02":"Haus",
							"04W04":"Wohnanlage (Invest.)",
							"07":"Prod./ Lager / Gewerbehallen",
							"08GAE":"Gaststätte",
							"04W02":"Einfamilienhaus (Invest.)",
							"01PENT":"Penthouse",
							"02EFH":"Einfamilienhaus",
							"04W01":"Eigentumswohnung (Invest.)",
							"02REH":"Reihenhaus",
							"04EZ":"Einkaufszentrum (Invest.)",
							"03GF":"Baugrund für Freizeit",
							"02VIL":"Villa",
							"04GA":"Gaststätte (Invest.)",
							"06B":"Büro",
							"04K":"Freizeitanlage (Invest.)",
							"08REST":"Restaurant",
							"01":"Wohnung",
							"08PENS":"Pension",
							"01DACH":"Dachgeschosswohnung",
							"04W05":"Wohn-/Geschäftshaus (Invest.)",
							"05":"Läden/SB-Märkte",
							"02DHH":"Doppelhaushälfte",
							"06BE":"Büroetage",
							"10":"Sonstige Immobilie",
							"07H":"Halle",
							"01TERR":"Terrassenwohnung",
							"01GERD":"Erdgeschosswohnung",
							"06PH":"Praxishaus",
							"06G":"Gewerbezentrum",
							"05F":"Verkaufshalle",
							"08B":"Bar",
							"07LHO":"Hochregallager",
							"07HI":"Industriehalle",
							"07HIF":"Industriehalle mit Freifläche",
							"10F":"Freizeitanlage",
							"10G":"Gewerbefläche",
							"06BH":"Bürohaus",
							"06BG":"Bürozentrum",
							"06BL":"Büro & Lagergebäude",
							"06P":"Praxis",
							"06PE":"Praxisetage",
							"05A":"Ausstellungsfläche",
							"05E1":"Einkaufszentrum",
							"05E2":"Kaufhaus",
							"05K":"Kiosk",
							"05L":"Laden",
							"11C":"Carport",
							"02REHM":"Reihenmittelhaus",
							"10W":"Werkstatt (Produktion)",
							"14DA":"Dachgeschoss (WG)",
							"16FA":"Fachwerkhaus (Typ)",
							"14MA":"Maisonette (WG)",
							"14PE":"Penthouse (WG)",
							"16DO":"Doppelhaus (Typ)",
							"15GA":"Garage/Sonstige (ZV)",
							"14SU":"Souterrain (WG)",
							"01ZROHD":"Rohdachboden (AUT)",
							"01ZATTIK":"Attikawohnung",
							"05E":"SB-Markt",
							"05LV":"Verkaufsfläche",
							"08C":"Cafe",
							"08D":"Diskothek",
							"08HOTA":"Hotelanwesen",
							"09A1":"Anwesen",
							"09A2":"Bauernhof",
							"09W":"Weingut",
							"04GWE":"Gewerbeeinheit (Invest.)",
							"04EG":"Geschäftshaus (Invest.)",
							"04GH":"Halle/Lager (Invest.)",
							"04E":"Laden/Verkaufsfläche (Invest.)",
							"04ES":"Supermarkt (Invest.)",
							"04B":"Bürogebäude (Invest.)",
							"04GWA":"Gewerbeanwesen (Invest.)",
							"04S":"Servicecenter (Invest.)",
							"04Z":"Sonstiges (Invest.)",
							"04GAH":"Hotel (Invest.)",
							"04GWI":"Industrieanwesen (Invest.)",
							"15EI":"Eigentumswohnung (ZV)",
							"16EI":"Einfamilienhaus (Typ)",
							"16LA":"Landhaus (Typ)",
							"14SO":"Sonstige (WG)",
							"16SV":"Stadtvilla (Typ)",
							"14":"WG-Zimmer (WG)",
							"15":"Zwangsversteigerung (ZV)",
							"16ZW":"Zweifamilienhaus (Typ)",
							"12A":"Appartement",
							"08F":"Ferienbungalows",
							"02EFE":"Einfamilienhaus mit Einliegerwohnung",
							"11G":"Garage",
							"11T":"Tiefgaragenstellplatz",
							"10GP":"Gewerbepark",
							"12H":"Haus",
							"12W":"Wohnung (WAZ)",
							"12Z":"Zimmer (WAZ)",
							"12":"Wohnen auf Zeit (WAZ)",
							"16BL":"Blockhaus (Typ)",
							"11S":"Stellplatz",
							"07A":"Ausstellungsfläche (Produktion)",
							"02BNG":"Bungalow",
							"02BURG":"Burg/Schloss",
							"06BUGE":"Büro- u. Geschäftsgebäude",
							"11D":"Duplex",
							"11":"Garage Stellplatz",
							"01HP":"Hochparterre",
							"11P":"Parkhausstellplatz",
							"02REHE":"Reiheneckhaus",
							"01SOUT":"Souterrain",
							"06WOGE":"Wohn- u. Geschäftsgebäude",
							"14ER":"Erdgeschoss (WG)",
							"08Beher":"Beherbergungsbetrieb",
							"03indust":"Baugrundstück für Wohnungen und Industrie",
							"03dup":"Baugrundstück für freistehende und Duplexhäuser",
							"03BM":"Baugrund für Mehrfamilienhäuser",
							"03BWG":"Baugrund für Wohnen und Gewerbe",
							"03GS":"Grundstück für Soziales",
							"04GW":"Industrie- und Gewerbeimmobilien (Invest.)",
							"04HI":"Handelsimmobilien (Invest.)",
							"04HIF":"Fachmarktzentrum (Invest.)",
							"04HIK":"Kaufhaus (Invest.)",
							"04SI":"Sozialimmobilien (Invest.)",
							"04SIB":"Betreutes Wohnen (Invest.)",
							"04SIP":"Pflegeheim (Invest.)",
							"04SIK":"Klinik (Invest.)",
							"04W":"Wohnimmobilien (Invest.)",
							"04ZP":"Parkhaus (Invest.)",
							"09F":"Fischzucht",
							"08PENT":"Boardinghaus",
							"11Z":"Sonstiges",
							"01LOFT":"Loftwohnung",
							"08HOTG":"Hotel garni",
							"01ETAG":"Etagenwohnung",
							"02DZH":"Zweifamilienhaus",
							"07LKÜ":"Kühlhaus",
							"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR":"Kühlregallager",
							"08GAHS":"Gästehaus",
							"07LFR":"Lager mit Freifläche",
							"07L":"Lagerfläche",
							"01ZO":"Sonstiger Wohnungstyp",
							"08":"Hotellerie- und Gastronomieflächen",
							"06A1":"Loft",
							"06":"Gewerbeflächen",
							"04W03":"Mehrfamilienhaus (Invest.)",
							"07LH":"Lagerhalle",
							"04":"Anlage-/Investmentobjekte",
							"07SF":"Servicefläche",
							"07LSP":"Speditionslager",
							"07W":"Werkstattsfläche",
							"02ZB":"Besondere Immobilie",
							"09R":"Reiterhof",
							"01MAIS":"Maisonettewohnung",
							"03GL":"Grundstück Land und Forstwirtschaft",
							"03":"Grundstücke",
							"10GE":"Gewerbeeinheit",
							"10S":"Spezialobjekt",
							"02LBH":"Bauernhaus",
							"03GG":"Baugrund für Gewerbe",
							"08HOT":"Hotel",
							"06A":"Atelier",
							"09":"Land- / Forstwirtschaft",
							"02":"Haus",
							"04W04":"Wohnanlage (Invest.)",
							"07":"Produktions- und Lagerflächen",
							"08GAE":"Gaststätte",
							"04W02":"Einfamilienhaus (Invest.)",
							"01PENT":"Penthouse",
							"02EFH":"Einfamilienhaus",
							"04W01":"Eigentumswohnung (Invest.)",
							"02REH":"Reihenhaus",
							"04HIE":"Einkaufszentrum (Invest.)",
							"03GF":"Baugrund für Freizeit",
							"02MFH":"Mehrfamilienhaus",
							"02EFE":"Einfamilienhaus mit Einliegerwohnung",
							"11G":"Garage",
							"11T":"Tiefgaragenstellplatz",
							"11S":"Stellplatz",
							"12A":"Apartment",
							"08F":"Ferienimmobilie",
							"10GP":"Gewerbepark",
							"12H":"Haus",
							"12W":"Wohnung",
							"12Z":"Zimmer",
							"07A":"Ausstellungsfläche (Produktion)",
							"02BNG":"Bungalow",
							"06BUGE":"Büro- und Geschäftsgebäude",
							"11C":"Carport",
							"11D":"Duplex",
							"11":"Garage Stellplatz",
							"01HP":"Hochparterre",
							"11P":"Parkhausstellplatz",
							"02REHM":"Reihenmittelhaus",
							"01SOUT":"Souterrain",
							"06WOGE":"Wohn- und Geschäftsgebäude",
							"02REHE":"Reiheneckhaus",
							"10W":"Werkstatt (Produktion)",
							"02VIL":"Villa",
							"04GA":"Gaststätte / Gasthaus (Invest.)",
							"06B":"Bürofläche",
							"04ZF":"Freizeitimmobilie (Invest.)",
							"08REST":"Restaurant",
							"01":"Wohnung",
							"08PENS":"Pension",
							"01DACH":"Dachgeschosswohnung",
							"04W05":"Wohn-/Geschäftshaus (Invest.)",
							"05":"Einzelhandelsflächen",
							"02DHH":"Doppelhaushälfte",
							"06BE":"Büroetage",
							"10":"Sonstige Objekte",
							"07H":"Halle",
							"01TERR":"Terrassenwohnung",
							"01GERD":"Erdgeschosswohnung",
							"06PH":"Praxishaus",
							"06G":"Gewerbezentrum",
							"05F":"Verkaufshalle",
							"08B":"Bar",
							"07LHO":"Hochregallager",
							"07HI":"Produktionsfläche",
							"07HIF":"Industriehalle mit Freifläche",
							"10F":"Freizeitanlage",
							"10G":"Gewerbefläche",
							"06BH":"Bürohaus",
							"06BG":"Bürozentrum",
							"06BL":"Büro und Lagergebäude",
							"06P":"Praxis",
							"06PE":"Praxisfläche",
							"05A":"Ausstellungsfläche",
							"05E1":"Einkaufszentrum",
							"05F1":"Factory Outlet",
							"05E2":"Kaufhaus",
							"05K":"Kiosk",
							"05L":"Laden",
							"05E":"SB-Markt",
							"05LV":"Verkaufsfläche",
							"08C":"Cafe",
							"08D":"Diskothek",
							"08HOTA":"Hotelanwesen",
							"09A1":"Anwesen",
							"09A2":"Bauernhof",
							"09W":"Weingut",
							"04GWE":"Gewerbeeinheit (Invest.)",
							"04GWG":"Geschäftshaus, Handel, Büro (Invest.)",
							"04GWH":"Halle/Lager (Invest.)",
							"04HIL":"Laden/Verkaufsfläche (Invest.)",
							"04HIS":"Supermarkt (Invest.)",
							"04GWB":"Bürogebäude (Invest.)",
							"04GWA":"Gewerbeanwesen (Invest.)",
							"04GWS":"Servicecenter (Invest.)",
							"04Z":"Sonstiges (Invest.)",
							"04GAH":"Hotel (Invest.)",
							"04GWI":"Industrieanwesen (Invest.)",
							"02BURG":"Burg/Schloss",
							"02SON":"Sonstige Häuser",
							"12":"Wohnen auf Zeit"
						}
					}
				},
				"addresses": {
					"addresses": {
						"caption":	"Lage",
						"type":		"addresses",
						"unit":		""
					}
				},
				"price":{
					"rent": {
						"caption":	"Miete zzgl. NK",
						"type":		"currence",
						"unit":		"€"
					},
					"rentinclusiveofheating": {
						"caption":	"Warmmiete",
						"type":		"currence",
						"unit":		"€"
					},
					"purchaseprice": {
						"caption":	"Kaufpreis",
						"type":		"currence",
						"unit":		"€"
					},
					"price_on_request": {
						"caption":	"Preis auf Anfrage",
						"type":		"yesno",
						"unit":		""
					},
					"tenancy": {
						"caption":	"Pacht",
						"type":		"currence",
						"unit":		"€"
					},
					"annuallease": {
						"caption":	"Jahrespacht",
						"type":		"currence",
						"unit":		"€"
					}
				},
				"geo":{
					"longitude":{
						"caption":	"longitude",
						"type":		"text",
						"unit":		""
					},
					"latitude":{
						"caption":	"latitude",
						"type":		"text",
						"unit":		""
					}
				}
			}
		},
		"details":{	
			"default":{
				"id": {
					"caption":	"id",
					"type":		"id",
					"unit":		""
				},
				"related":{
					"parent": {
						"caption":	"Weitere Einheiten im Objekt",
						"type":		"related",
						"unit":		"",
						"fields": {
							"estatetype": {
								"caption":	"Art",
								"type":		"option",
								"unit":		"",
								"option":	{
									"15EM":"Ein/Mehrfamilienhaus (ZV)",
									"16EM":"EinfamilienhausMitEinliegerwohnung (Typ)",
									"15GE":"Gewerbe/Anlage (ZV)",
									"16HO":"Holzhaus (Typ)",
									"14LO":"Loft (WG)",
									"14TE":"Terrassenwohnung (WG)",
									"16":"Typenhäuser (Typ)",
									"02REND":"Reihenendhaus",
									"02ZSTAD":"Stadthaus",
									"02ZREST":"Resthof",
									"02ZLAND":"Landhaus",
									"02ZBERG":"Berghütte",
									"02ZCHAL":"Chalet",
									"02ZSTRA":"Strandhaus",
									"02ZLAUB":"Laube/Datsche/Gartenhaus",
									"02ZAPAH":"Apartmenthaus",
									"02ZHERR":"Herrenhaus",
									"02ZFINC":"Finca",
									"02ZRUST":"Rustico",
									"02ZFERT":"Fertighaus",
									"03INDU":"Baugrund für Industrie",
									"03GEMI":"Gemischte Nutzung",
									"03GEWE":"Gewerbepark",
									"03SOND":"Sondernutzung",
									"03SEEL":"Seeliegenschaft",
									"05EINHA":"Einzelhandelsladen",
									"05VERBR":"Verbrauchermarkt",
									"01ZAPART":"Apartment",
									"01ZFERIE":"Ferienwohnung",
									"01ZGALER":"Galerie",
									"08GASTW":"Gastronomie mit Wohnung",
									"08BEHERB":"Weitere Beherbergungsbetriebe",
									"08RAUCH":"Raucherlokal",
									"08EINRA":"Einraumlokal",
									"07PROD":"Produktion",
									"07FREIF":"Freiflächen",
									"09AUSS":"Aussiedlerhof",
									"09GART":"Gartenbau",
									"09ACKE":"Ackerbau",
									"09VIEH":"Viehwirtschaft",
									"09JAGD":"Jagd- u. Forstwirtschaft",
									"09TEICH":"Teich- u. Fischwirtschaft",
									"09SCHEU":"Scheunen",
									"09SONST":"Sonstige Landwirtschaftsimmobilien",
									"09JAGDR":"Jagdrevier",
									"11DOPP":"Doppelgarage",
									"11BOOT":"Bootsliegeplatz",
									"11EINZE":"Einzelgarage",
									"11STROM":"Parkplatz-Strom",
									"04VERB":"Verbrauchermärkte (Invest)",
									"04PFLEG":"Pflegeheim (Invest)",
									"04SANAT":"Sanatorium (Invest)",
									"04SENIO":"Seniorenheim (Invest)",
									"04CBETRE":"Betreutes Wohnen (Invest)",
									"20":"Freizeitimmobilien gewerblich",
									"20SPORT":"Sportanlagen",
									"20VERGN":"Vergnügungspark/-Center",
									"21":"Sonstige Typen",
									"21PARKH":"Parkhaus",
									"21TANKS":"Tankstelle",
									"21KRANK":"Krankenhaus",
									"21SONST":"Sonstige",
									"15GR":"Grundstück (ZV)",
									"02SON":"sonstige Häuser",
									"01LOFT":"Loftwohnung",
									"02MFH":"Mehrfamilienhaus",
									"08HOTG":"Hotel garni",
									"01ETAG":"Etagenwohnung",
									"02DZH":"Zweifamilienhaus",
									"07LKÜ":"Kühlhaus",
									"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
									"07LKÜR":"Kühlregallager",
									"08GAHS":"Gästehaus",
									"07LFR":"Lager mit Freifläche",
									"07L":"Lagerfläche",
									"01ZO":"sonstiger Wohnungstyp",
									"08":"Gastronomie / Beherbergungen",
									"06A1":"Loft",
									"06":"Büro / Praxis / Ausstellungsräume",
									"04W03":"Mehrfamilienhaus (Invest.)",
									"07LH":"Lagerhalle",
									"04":"Anlage-/Investmentobjekte",
									"07SF":"Servicefläche",
									"07LSP":"Speditionslager",
									"07W":"Werkstatt",
									"02ZB":"besondere Immobilie",
									"09R":"Reiterhof",
									"01MAIS":"Maisonettewohnung",
									"03GL":"Grundstück Land und Forstwirtschaft",
									"03":"Grundstücke",
									"10GE":"Gewerbeeinheit",
									"10S":"Spezialobjekt",
									"02LBH":"Bauernhaus",
									"03GG":"Baugrund für Gewerbe",
									"08HOT":"Hotel",
									"06A":"Atelier",
									"09":"Land- / Forstwirtschaft",
									"02":"Haus",
									"04W04":"Wohnanlage (Invest.)",
									"07":"Prod./ Lager / Gewerbehallen",
									"08GAE":"Gaststätte",
									"04W02":"Einfamilienhaus (Invest.)",
									"01PENT":"Penthouse",
									"02EFH":"Einfamilienhaus",
									"04W01":"Eigentumswohnung (Invest.)",
									"02REH":"Reihenhaus",
									"04EZ":"Einkaufszentrum (Invest.)",
									"03GF":"Baugrund für Freizeit",
									"02VIL":"Villa",
									"04GA":"Gaststätte (Invest.)",
									"06B":"Büro",
									"04K":"Freizeitanlage (Invest.)",
									"08REST":"Restaurant",
									"01":"Wohnung",
									"08PENS":"Pension",
									"01DACH":"Dachgeschosswohnung",
									"04W05":"Wohn-/Geschäftshaus (Invest.)",
									"05":"Läden/SB-Märkte",
									"02DHH":"Doppelhaushälfte",
									"06BE":"Büroetage",
									"10":"Sonstige Immobilie",
									"07H":"Halle",
									"01TERR":"Terrassenwohnung",
									"01GERD":"Erdgeschosswohnung",
									"06PH":"Praxishaus",
									"06G":"Gewerbezentrum",
									"05F":"Verkaufshalle",
									"08B":"Bar",
									"07LHO":"Hochregallager",
									"07HI":"Industriehalle",
									"07HIF":"Industriehalle mit Freifläche",
									"10F":"Freizeitanlage",
									"10G":"Gewerbefläche",
									"06BH":"Bürohaus",
									"06BG":"Bürozentrum",
									"06BL":"Büro & Lagergebäude",
									"06P":"Praxis",
									"06PE":"Praxisetage",
									"05A":"Ausstellungsfläche",
									"05E1":"Einkaufszentrum",
									"05E2":"Kaufhaus",
									"05K":"Kiosk",
									"05L":"Laden",
									"11C":"Carport",
									"02REHM":"Reihenmittelhaus",
									"10W":"Werkstatt (Produktion)",
									"14DA":"Dachgeschoss (WG)",
									"16FA":"Fachwerkhaus (Typ)",
									"14MA":"Maisonette (WG)",
									"14PE":"Penthouse (WG)",
									"16DO":"Doppelhaus (Typ)",
									"15GA":"Garage/Sonstige (ZV)",
									"14SU":"Souterrain (WG)",
									"01ZROHD":"Rohdachboden (AUT)",
									"01ZATTIK":"Attikawohnung",
									"05E":"SB-Markt",
									"05LV":"Verkaufsfläche",
									"08C":"Cafe",
									"08D":"Diskothek",
									"08HOTA":"Hotelanwesen",
									"09A1":"Anwesen",
									"09A2":"Bauernhof",
									"09W":"Weingut",
									"04GWE":"Gewerbeeinheit (Invest.)",
									"04EG":"Geschäftshaus (Invest.)",
									"04GH":"Halle/Lager (Invest.)",
									"04E":"Laden/Verkaufsfläche (Invest.)",
									"04ES":"Supermarkt (Invest.)",
									"04B":"Bürogebäude (Invest.)",
									"04GWA":"Gewerbeanwesen (Invest.)",
									"04S":"Servicecenter (Invest.)",
									"04Z":"Sonstiges (Invest.)",
									"04GAH":"Hotel (Invest.)",
									"04GWI":"Industrieanwesen (Invest.)",
									"15EI":"Eigentumswohnung (ZV)",
									"16EI":"Einfamilienhaus (Typ)",
									"16LA":"Landhaus (Typ)",
									"14SO":"Sonstige (WG)",
									"16SV":"Stadtvilla (Typ)",
									"14":"WG-Zimmer (WG)",
									"15":"Zwangsversteigerung (ZV)",
									"16ZW":"Zweifamilienhaus (Typ)",
									"12A":"Appartement",
									"08F":"Ferienbungalows",
									"02EFE":"Einfamilienhaus mit Einliegerwohnung",
									"11G":"Garage",
									"11T":"Tiefgaragenstellplatz",
									"10GP":"Gewerbepark",
									"12H":"Haus",
									"12W":"Wohnung (WAZ)",
									"12Z":"Zimmer (WAZ)",
									"12":"Wohnen auf Zeit (WAZ)",
									"16BL":"Blockhaus (Typ)",
									"11S":"Stellplatz",
									"07A":"Ausstellungsfläche (Produktion)",
									"02BNG":"Bungalow",
									"02BURG":"Burg/Schloss",
									"06BUGE":"Büro- u. Geschäftsgebäude",
									"11D":"Duplex",
									"11":"Garage Stellplatz",
									"01HP":"Hochparterre",
									"11P":"Parkhausstellplatz",
									"02REHE":"Reiheneckhaus",
									"01SOUT":"Souterrain",
									"06WOGE":"Wohn- u. Geschäftsgebäude",
									"14ER":"Erdgeschoss (WG)",
									"08Beher":"Beherbergungsbetrieb",
									"03indust":"Baugrundstück für Wohnungen und Industrie",
									"03dup":"Baugrundstück für freistehende und Duplexhäuser",
									"03BM":"Baugrund für Mehrfamilienhäuser",
									"03BWG":"Baugrund für Wohnen und Gewerbe",
									"03GS":"Grundstück für Soziales",
									"04GW":"Industrie- und Gewerbeimmobilien (Invest.)",
									"04HI":"Handelsimmobilien (Invest.)",
									"04HIF":"Fachmarktzentrum (Invest.)",
									"04HIK":"Kaufhaus (Invest.)",
									"04SI":"Sozialimmobilien (Invest.)",
									"04SIB":"Betreutes Wohnen (Invest.)",
									"04SIP":"Pflegeheim (Invest.)",
									"04SIK":"Klinik (Invest.)",
									"04W":"Wohnimmobilien (Invest.)",
									"04ZP":"Parkhaus (Invest.)",
									"09F":"Fischzucht",
									"08PENT":"Boardinghaus",
									"11Z":"Sonstiges",
									"01LOFT":"Loftwohnung",
									"08HOTG":"Hotel garni",
									"01ETAG":"Etagenwohnung",
									"02DZH":"Zweifamilienhaus",
									"07LKÜ":"Kühlhaus",
									"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
									"07LKÜR":"Kühlregallager",
									"08GAHS":"Gästehaus",
									"07LFR":"Lager mit Freifläche",
									"07L":"Lagerfläche",
									"01ZO":"Sonstiger Wohnungstyp",
									"08":"Hotellerie- und Gastronomieflächen",
									"06A1":"Loft",
									"06":"Gewerbeflächen",
									"04W03":"Mehrfamilienhaus (Invest.)",
									"07LH":"Lagerhalle",
									"04":"Anlage-/Investmentobjekte",
									"07SF":"Servicefläche",
									"07LSP":"Speditionslager",
									"07W":"Werkstattsfläche",
									"02ZB":"Besondere Immobilie",
									"09R":"Reiterhof",
									"01MAIS":"Maisonettewohnung",
									"03GL":"Grundstück Land und Forstwirtschaft",
									"03":"Grundstücke",
									"10GE":"Gewerbeeinheit",
									"10S":"Spezialobjekt",
									"02LBH":"Bauernhaus",
									"03GG":"Baugrund für Gewerbe",
									"08HOT":"Hotel",
									"06A":"Atelier",
									"09":"Land- / Forstwirtschaft",
									"02":"Haus",
									"04W04":"Wohnanlage (Invest.)",
									"07":"Produktions- und Lagerflächen",
									"08GAE":"Gaststätte",
									"04W02":"Einfamilienhaus (Invest.)",
									"01PENT":"Penthouse",
									"02EFH":"Einfamilienhaus",
									"04W01":"Eigentumswohnung (Invest.)",
									"02REH":"Reihenhaus",
									"04HIE":"Einkaufszentrum (Invest.)",
									"03GF":"Baugrund für Freizeit",
									"02MFH":"Mehrfamilienhaus",
									"02EFE":"Einfamilienhaus mit Einliegerwohnung",
									"11G":"Garage",
									"11T":"Tiefgaragenstellplatz",
									"11S":"Stellplatz",
									"12A":"Apartment",
									"08F":"Ferienimmobilie",
									"10GP":"Gewerbepark",
									"12H":"Haus",
									"12W":"Wohnung",
									"12Z":"Zimmer",
									"07A":"Ausstellungsfläche (Produktion)",
									"02BNG":"Bungalow",
									"06BUGE":"Büro- und Geschäftsgebäude",
									"11C":"Carport",
									"11D":"Duplex",
									"11":"Garage Stellplatz",
									"01HP":"Hochparterre",
									"11P":"Parkhausstellplatz",
									"02REHM":"Reihenmittelhaus",
									"01SOUT":"Souterrain",
									"06WOGE":"Wohn- und Geschäftsgebäude",
									"02REHE":"Reiheneckhaus",
									"10W":"Werkstatt (Produktion)",
									"02VIL":"Villa",
									"04GA":"Gaststätte / Gasthaus (Invest.)",
									"06B":"Bürofläche",
									"04ZF":"Freizeitimmobilie (Invest.)",
									"08REST":"Restaurant",
									"01":"Wohnung",
									"08PENS":"Pension",
									"01DACH":"Dachgeschosswohnung",
									"04W05":"Wohn-/Geschäftshaus (Invest.)",
									"05":"Einzelhandelsflächen",
									"02DHH":"Doppelhaushälfte",
									"06BE":"Büroetage",
									"10":"Sonstige Objekte",
									"07H":"Halle",
									"01TERR":"Terrassenwohnung",
									"01GERD":"Erdgeschosswohnung",
									"06PH":"Praxishaus",
									"06G":"Gewerbezentrum",
									"05F":"Verkaufshalle",
									"08B":"Bar",
									"07LHO":"Hochregallager",
									"07HI":"Produktionsfläche",
									"07HIF":"Industriehalle mit Freifläche",
									"10F":"Freizeitanlage",
									"10G":"Gewerbefläche",
									"06BH":"Bürohaus",
									"06BG":"Bürozentrum",
									"06BL":"Büro und Lagergebäude",
									"06P":"Praxis",
									"06PE":"Praxisfläche",
									"05A":"Ausstellungsfläche",
									"05E1":"Einkaufszentrum",
									"05F1":"Factory Outlet",
									"05E2":"Kaufhaus",
									"05K":"Kiosk",
									"05L":"Laden",
									"05E":"SB-Markt",
									"05LV":"Verkaufsfläche",
									"08C":"Cafe",
									"08D":"Diskothek",
									"08HOTA":"Hotelanwesen",
									"09A1":"Anwesen",
									"09A2":"Bauernhof",
									"09W":"Weingut",
									"04GWE":"Gewerbeeinheit (Invest.)",
									"04GWG":"Geschäftshaus, Handel, Büro (Invest.)",
									"04GWH":"Halle/Lager (Invest.)",
									"04HIL":"Laden/Verkaufsfläche (Invest.)",
									"04HIS":"Supermarkt (Invest.)",
									"04GWB":"Bürogebäude (Invest.)",
									"04GWA":"Gewerbeanwesen (Invest.)",
									"04GWS":"Servicecenter (Invest.)",
									"04Z":"Sonstiges (Invest.)",
									"04GAH":"Hotel (Invest.)",
									"04GWI":"Industrieanwesen (Invest.)",
									"02BURG":"Burg/Schloss",
									"02SON":"Sonstige Häuser",
									"12":"Wohnen auf Zeit"
								}
							},	
							"purchaseprice": {
								"caption":	"Kaufpreis",
								"type":		"currence",
								"unit":		"€"
							},
							"livingSpace": {
								"caption":	"Wohnfläche",
								"type":		"area",
								"unit":		"m²"
							},
							"numbersOfRooms": {
								"caption":	"Zimmer",
								"type":		"number",
								"unit":		""
							}
						}	
					}
				},	
				"contact":{
					"contact": {
						"caption":	"Ansprechpartner",
						"type":		"contact",
						"unit":		""
					}
				},
				"mainImage":{
					"mainImage": {
						"caption":	"Titlebild",
						"type":		"image",
						"unit":		""
					},
					"onlineImage": {
						"caption":	"Titlebild",
						"type":		"image",
						"unit":		""
					}
				},
				"groundplot":{
					"groundplotImage": {
						"caption":	"Grundriss",
						"type":		"image",
						"unit":		""
					}
				},
				"headerBar": {
					"headline": {
						"caption":	"headline",
						"type":		"text",
						"unit":		""
					},
					"identifier": {
						"caption":	"identifier",
						"type":		"text",
						"unit":		""
					}
				},
				"description": {
					"textEstate": {
						"caption":	"Immobilie",
						"type":		"text",
						"unit":		""
					},
					"textLocation": {
						"caption":	"Umfeld der Immobilie",
						"type":		"text",
						"unit":		""
					},
					"textEnvironment": {
						"caption":	"Ausstattung der Immobilie",
						"type":		"text",
						"unit":		""
					},
					"textConstructability": {
						"caption":	"Bebaubarkeit",
						"type":		"text",
						"unit":		""
					},
					"textDevelopment": {
						"caption":	"Erschließung",
						"type":		"text",
						"unit":		""
					},
					"textFree": {
						"caption":	"Sonstiges",
						"type":		"text",
						"unit":		""
					},
          "linkpropertyvideo": {
						"caption":	"Immobilien-Video",
						"type":		"text",
						"unit":		""
					}
				},
				"legal": {
					"commissionInformation": {
						"caption":	"Rechtliches",
						"type":		"text",
						"unit":		""
					}
				},
				"facts": {
					"estatetype": {
						"caption":	"Immobilie",
						"type":		"option",
						"unit":		"",
						"option":	{
							"15EM":"Ein/Mehrfamilienhaus (ZV)",
							"16EM":"EinfamilienhausMitEinliegerwohnung (Typ)",
							"15GE":"Gewerbe/Anlage (ZV)",
							"16HO":"Holzhaus (Typ)",
							"14LO":"Loft (WG)",
							"14TE":"Terrassenwohnung (WG)",
							"16":"Typenhäuser (Typ)",
							"02REND":"Reihenendhaus",
							"02ZSTAD":"Stadthaus",
							"02ZREST":"Resthof",
							"02ZLAND":"Landhaus",
							"02ZBERG":"Berghütte",
							"02ZCHAL":"Chalet",
							"02ZSTRA":"Strandhaus",
							"02ZLAUB":"Laube/Datsche/Gartenhaus",
							"02ZAPAH":"Apartmenthaus",
							"02ZHERR":"Herrenhaus",
							"02ZFINC":"Finca",
							"02ZRUST":"Rustico",
							"02ZFERT":"Fertighaus",
							"03INDU":"Baugrund für Industrie",
							"03GEMI":"Gemischte Nutzung",
							"03GEWE":"Gewerbepark",
							"03SOND":"Sondernutzung",
							"03SEEL":"Seeliegenschaft",
							"05EINHA":"Einzelhandelsladen",
							"05VERBR":"Verbrauchermarkt",
							"01ZAPART":"Apartment",
							"01ZFERIE":"Ferienwohnung",
							"01ZGALER":"Galerie",
							"08GASTW":"Gastronomie mit Wohnung",
							"08BEHERB":"Weitere Beherbergungsbetriebe",
							"08RAUCH":"Raucherlokal",
							"08EINRA":"Einraumlokal",
							"07PROD":"Produktion",
							"07FREIF":"Freiflächen",
							"09AUSS":"Aussiedlerhof",
							"09GART":"Gartenbau",
							"09ACKE":"Ackerbau",
							"09VIEH":"Viehwirtschaft",
							"09JAGD":"Jagd- u. Forstwirtschaft",
							"09TEICH":"Teich- u. Fischwirtschaft",
							"09SCHEU":"Scheunen",
							"09SONST":"Sonstige Landwirtschaftsimmobilien",
							"09JAGDR":"Jagdrevier",
							"11DOPP":"Doppelgarage",
							"11BOOT":"Bootsliegeplatz",
							"11EINZE":"Einzelgarage",
							"11STROM":"Parkplatz-Strom",
							"04VERB":"Verbrauchermärkte (Invest)",
							"04PFLEG":"Pflegeheim (Invest)",
							"04SANAT":"Sanatorium (Invest)",
							"04SENIO":"Seniorenheim (Invest)",
							"04CBETRE":"Betreutes Wohnen (Invest)",
							"20":"Freizeitimmobilien gewerblich",
							"20SPORT":"Sportanlagen",
							"20VERGN":"Vergnügungspark/-Center",
							"21":"Sonstige Typen",
							"21PARKH":"Parkhaus",
							"21TANKS":"Tankstelle",
							"21KRANK":"Krankenhaus",
							"21SONST":"Sonstige",
							"15GR":"Grundstück (ZV)",
							"02SON":"sonstige Häuser",
							"01LOFT":"Loftwohnung",
							"02MFH":"Mehrfamilienhaus",
							"08HOTG":"Hotel garni",
							"01ETAG":"Etagenwohnung",
							"02DZH":"Zweifamilienhaus",
							"07LKÜ":"Kühlhaus",
							"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR":"Kühlregallager",
							"08GAHS":"Gästehaus",
							"07LFR":"Lager mit Freifläche",
							"07L":"Lagerfläche",
							"01ZO":"sonstiger Wohnungstyp",
							"08":"Gastronomie / Beherbergungen",
							"06A1":"Loft",
							"06":"Büro / Praxis / Ausstellungsräume",
							"04W03":"Mehrfamilienhaus (Invest.)",
							"07LH":"Lagerhalle",
							"04":"Anlage-/Investmentobjekte",
							"07SF":"Servicefläche",
							"07LSP":"Speditionslager",
							"07W":"Werkstatt",
							"02ZB":"besondere Immobilie",
							"09R":"Reiterhof",
							"01MAIS":"Maisonettewohnung",
							"03GL":"Grundstück Land und Forstwirtschaft",
							"03":"Grundstücke",
							"10GE":"Gewerbeeinheit",
							"10S":"Spezialobjekt",
							"02LBH":"Bauernhaus",
							"03GG":"Baugrund für Gewerbe",
							"08HOT":"Hotel",
							"06A":"Atelier",
							"09":"Land- / Forstwirtschaft",
							"02":"Haus",
							"04W04":"Wohnanlage (Invest.)",
							"07":"Prod./ Lager / Gewerbehallen",
							"08GAE":"Gaststätte",
							"04W02":"Einfamilienhaus (Invest.)",
							"01PENT":"Penthouse",
							"02EFH":"Einfamilienhaus",
							"04W01":"Eigentumswohnung (Invest.)",
							"02REH":"Reihenhaus",
							"04EZ":"Einkaufszentrum (Invest.)",
							"03GF":"Baugrund für Freizeit",
							"02VIL":"Villa",
							"04GA":"Gaststätte (Invest.)",
							"06B":"Büro",
							"04K":"Freizeitanlage (Invest.)",
							"08REST":"Restaurant",
							"01":"Wohnung",
							"08PENS":"Pension",
							"01DACH":"Dachgeschosswohnung",
							"04W05":"Wohn-/Geschäftshaus (Invest.)",
							"05":"Läden/SB-Märkte",
							"02DHH":"Doppelhaushälfte",
							"06BE":"Büroetage",
							"10":"Sonstige Immobilie",
							"07H":"Halle",
							"01TERR":"Terrassenwohnung",
							"01GERD":"Erdgeschosswohnung",
							"06PH":"Praxishaus",
							"06G":"Gewerbezentrum",
							"05F":"Verkaufshalle",
							"08B":"Bar",
							"07LHO":"Hochregallager",
							"07HI":"Industriehalle",
							"07HIF":"Industriehalle mit Freifläche",
							"10F":"Freizeitanlage",
							"10G":"Gewerbefläche",
							"06BH":"Bürohaus",
							"06BG":"Bürozentrum",
							"06BL":"Büro & Lagergebäude",
							"06P":"Praxis",
							"06PE":"Praxisetage",
							"05A":"Ausstellungsfläche",
							"05E1":"Einkaufszentrum",
							"05E2":"Kaufhaus",
							"05K":"Kiosk",
							"05L":"Laden",
							"11C":"Carport",
							"02REHM":"Reihenmittelhaus",
							"10W":"Werkstatt (Produktion)",
							"14DA":"Dachgeschoss (WG)",
							"16FA":"Fachwerkhaus (Typ)",
							"14MA":"Maisonette (WG)",
							"14PE":"Penthouse (WG)",
							"16DO":"Doppelhaus (Typ)",
							"15GA":"Garage/Sonstige (ZV)",
							"14SU":"Souterrain (WG)",
							"01ZROHD":"Rohdachboden (AUT)",
							"01ZATTIK":"Attikawohnung",
							"05E":"SB-Markt",
							"05LV":"Verkaufsfläche",
							"08C":"Cafe",
							"08D":"Diskothek",
							"08HOTA":"Hotelanwesen",
							"09A1":"Anwesen",
							"09A2":"Bauernhof",
							"09W":"Weingut",
							"04GWE":"Gewerbeeinheit (Invest.)",
							"04EG":"Geschäftshaus (Invest.)",
							"04GH":"Halle/Lager (Invest.)",
							"04E":"Laden/Verkaufsfläche (Invest.)",
							"04ES":"Supermarkt (Invest.)",
							"04B":"Bürogebäude (Invest.)",
							"04GWA":"Gewerbeanwesen (Invest.)",
							"04S":"Servicecenter (Invest.)",
							"04Z":"Sonstiges (Invest.)",
							"04GAH":"Hotel (Invest.)",
							"04GWI":"Industrieanwesen (Invest.)",
							"15EI":"Eigentumswohnung (ZV)",
							"16EI":"Einfamilienhaus (Typ)",
							"16LA":"Landhaus (Typ)",
							"14SO":"Sonstige (WG)",
							"16SV":"Stadtvilla (Typ)",
							"14":"WG-Zimmer (WG)",
							"15":"Zwangsversteigerung (ZV)",
							"16ZW":"Zweifamilienhaus (Typ)",
							"12A":"Appartement",
							"08F":"Ferienbungalows",
							"02EFE":"Einfamilienhaus mit Einliegerwohnung",
							"11G":"Garage",
							"11T":"Tiefgaragenstellplatz",
							"10GP":"Gewerbepark",
							"12H":"Haus",
							"12W":"Wohnung (WAZ)",
							"12Z":"Zimmer (WAZ)",
							"12":"Wohnen auf Zeit (WAZ)",
							"16BL":"Blockhaus (Typ)",
							"11S":"Stellplatz",
							"07A":"Ausstellungsfläche (Produktion)",
							"02BNG":"Bungalow",
							"02BURG":"Burg/Schloss",
							"06BUGE":"Büro- u. Geschäftsgebäude",
							"11D":"Duplex",
							"11":"Garage Stellplatz",
							"01HP":"Hochparterre",
							"11P":"Parkhausstellplatz",
							"02REHE":"Reiheneckhaus",
							"01SOUT":"Souterrain",
							"06WOGE":"Wohn- u. Geschäftsgebäude",
							"14ER":"Erdgeschoss (WG)",
							"08Beher":"Beherbergungsbetrieb",
							"03indust":"Baugrundstück für Wohnungen und Industrie",
							"03dup":"Baugrundstück für freistehende und Duplexhäuser",
							"03BM":"Baugrund für Mehrfamilienhäuser",
							"03BWG":"Baugrund für Wohnen und Gewerbe",
							"03GS":"Grundstück für Soziales",
							"04GW":"Industrie- und Gewerbeimmobilien (Invest.)",
							"04HI":"Handelsimmobilien (Invest.)",
							"04HIF":"Fachmarktzentrum (Invest.)",
							"04HIK":"Kaufhaus (Invest.)",
							"04SI":"Sozialimmobilien (Invest.)",
							"04SIB":"Betreutes Wohnen (Invest.)",
							"04SIP":"Pflegeheim (Invest.)",
							"04SIK":"Klinik (Invest.)",
							"04W":"Wohnimmobilien (Invest.)",
							"04ZP":"Parkhaus (Invest.)",
							"09F":"Fischzucht",
							"08PENT":"Boardinghaus",
							"11Z":"Sonstiges",
							"01LOFT":"Loftwohnung",
							"08HOTG":"Hotel garni",
							"01ETAG":"Etagenwohnung",
							"02DZH":"Zweifamilienhaus",
							"07LKÜ":"Kühlhaus",
							"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR":"Kühlregallager",
							"08GAHS":"Gästehaus",
							"07LFR":"Lager mit Freifläche",
							"07L":"Lagerfläche",
							"01ZO":"Sonstiger Wohnungstyp",
							"08":"Hotellerie- und Gastronomieflächen",
							"06A1":"Loft",
							"06":"Gewerbeflächen",
							"04W03":"Mehrfamilienhaus (Invest.)",
							"07LH":"Lagerhalle",
							"04":"Anlage-/Investmentobjekte",
							"07SF":"Servicefläche",
							"07LSP":"Speditionslager",
							"07W":"Werkstattsfläche",
							"02ZB":"Besondere Immobilie",
							"09R":"Reiterhof",
							"01MAIS":"Maisonettewohnung",
							"03GL":"Grundstück Land und Forstwirtschaft",
							"03":"Grundstücke",
							"10GE":"Gewerbeeinheit",
							"10S":"Spezialobjekt",
							"02LBH":"Bauernhaus",
							"03GG":"Baugrund für Gewerbe",
							"08HOT":"Hotel",
							"06A":"Atelier",
							"09":"Land- / Forstwirtschaft",
							"02":"Haus",
							"04W04":"Wohnanlage (Invest.)",
							"07":"Produktions- und Lagerflächen",
							"08GAE":"Gaststätte",
							"04W02":"Einfamilienhaus (Invest.)",
							"01PENT":"Penthouse",
							"02EFH":"Einfamilienhaus",
							"04W01":"Eigentumswohnung (Invest.)",
							"02REH":"Reihenhaus",
							"04HIE":"Einkaufszentrum (Invest.)",
							"03GF":"Baugrund für Freizeit",
							"02MFH":"Mehrfamilienhaus",
							"02EFE":"Einfamilienhaus mit Einliegerwohnung",
							"11G":"Garage",
							"11T":"Tiefgaragenstellplatz",
							"11S":"Stellplatz",
							"12A":"Apartment",
							"08F":"Ferienimmobilie",
							"10GP":"Gewerbepark",
							"12H":"Haus",
							"12W":"Wohnung",
							"12Z":"Zimmer",
							"07A":"Ausstellungsfläche (Produktion)",
							"02BNG":"Bungalow",
							"06BUGE":"Büro- und Geschäftsgebäude",
							"11C":"Carport",
							"11D":"Duplex",
							"11":"Garage Stellplatz",
							"01HP":"Hochparterre",
							"11P":"Parkhausstellplatz",
							"02REHM":"Reihenmittelhaus",
							"01SOUT":"Souterrain",
							"06WOGE":"Wohn- und Geschäftsgebäude",
							"02REHE":"Reiheneckhaus",
							"10W":"Werkstatt (Produktion)",
							"02VIL":"Villa",
							"04GA":"Gaststätte / Gasthaus (Invest.)",
							"06B":"Bürofläche",
							"04ZF":"Freizeitimmobilie (Invest.)",
							"08REST":"Restaurant",
							"01":"Wohnung",
							"08PENS":"Pension",
							"01DACH":"Dachgeschosswohnung",
							"04W05":"Wohn-/Geschäftshaus (Invest.)",
							"05":"Einzelhandelsflächen",
							"02DHH":"Doppelhaushälfte",
							"06BE":"Büroetage",
							"10":"Sonstige Objekte",
							"07H":"Halle",
							"01TERR":"Terrassenwohnung",
							"01GERD":"Erdgeschosswohnung",
							"06PH":"Praxishaus",
							"06G":"Gewerbezentrum",
							"05F":"Verkaufshalle",
							"08B":"Bar",
							"07LHO":"Hochregallager",
							"07HI":"Produktionsfläche",
							"07HIF":"Industriehalle mit Freifläche",
							"10F":"Freizeitanlage",
							"10G":"Gewerbefläche",
							"06BH":"Bürohaus",
							"06BG":"Bürozentrum",
							"06BL":"Büro und Lagergebäude",
							"06P":"Praxis",
							"06PE":"Praxisfläche",
							"05A":"Ausstellungsfläche",
							"05E1":"Einkaufszentrum",
							"05F1":"Factory Outlet",
							"05E2":"Kaufhaus",
							"05K":"Kiosk",
							"05L":"Laden",
							"05E":"SB-Markt",
							"05LV":"Verkaufsfläche",
							"08C":"Cafe",
							"08D":"Diskothek",
							"08HOTA":"Hotelanwesen",
							"09A1":"Anwesen",
							"09A2":"Bauernhof",
							"09W":"Weingut",
							"04GWE":"Gewerbeeinheit (Invest.)",
							"04GWG":"Geschäftshaus, Handel, Büro (Invest.)",
							"04GWH":"Halle/Lager (Invest.)",
							"04HIL":"Laden/Verkaufsfläche (Invest.)",
							"04HIS":"Supermarkt (Invest.)",
							"04GWB":"Bürogebäude (Invest.)",
							"04GWA":"Gewerbeanwesen (Invest.)",
							"04GWS":"Servicecenter (Invest.)",
							"04Z":"Sonstiges (Invest.)",
							"04GAH":"Hotel (Invest.)",
							"04GWI":"Industrieanwesen (Invest.)",
							"02BURG":"Burg/Schloss",
							"02SON":"Sonstige Häuser",
							"12":"Wohnen auf Zeit"
						}
					},
					"addresses": {
						"caption":	"Lage",
						"type":		"addresses",
						"unit":		""
					}
				},
				"linkTour":{	
					"link360": {
						"caption":	"360° Tour",
						"type":		"text",
						"unit":		""
					}
				},
				"details":{	
					"rent": {
						"caption":	"Miete zzgl. NK",
						"type":		"currence",
						"unit":		"€"
					},
					"rentinclusiveofheating": {
						"caption":	"Warmmiete",
						"type":		"currence",
						"unit":		"€"
					},
					"purchaseprice": {
						"caption":	"Kaufpreis",
						"type":		"currence",
						"unit":		"€"
					},
					"pricesqm": {
						"caption":	"Kaufpreis pro m²",
						"type":		"currence",
						"unit":		"€"
					},
					"rentsqf": {
						"caption":	"Mietpreis pro m²",
						"type":		"currence",
						"unit":		"€"
					},
					"price_on_request": {
						"caption":	"Preis auf Anfrage",
						"type":		"yesno",
						"unit":		""
					},
					"tenancy": {
						"caption":	"Pacht",
						"type":		"currence",
						"unit":		"€"
					},
					"minimumtermoflease": {
						"caption" : "Mindestmietdauer",
						"type": "number",
						"unit": "Monate"
					},
					"maxrentingtime": {
						"caption" : "Maximale Mietdauer",
						"type": "number",
						"unit": "Monate"
					},
					"availableFrom": {
						"caption" : "Verfügbar ab",
						"type": "date",
						"unit": ""
					},
					"availableUntil": {
						"caption": "Verfügbar bis",
						"type": "date",
						"unit": ""
					},
					"access": {
						"caption": "Zugang ab",
						"type": "date",
						"unit": ""
					},
					"service_charge": {
						"caption":	"Hausgeld",
						"type":		"currence",
						"unit":		"€"
					},
					"additionalexpenses": {
						"caption":	"Nebenkosten",
						"type":		"currence",
						"unit":		"€"
					},
					"service_charge": {
						"caption":	"Hausgeld",
						"type":		"currence",
						"unit":		"€"
					},
					"livingSpace": {
						"caption":	"Wohnfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"plotfront": {
						"caption":	"Grundstücksfront",
						"type":		"area",
						"unit":		"m"
					},
					"plotArea": {
						"caption":	"Grundstück",
						"type":		"area",
						"unit":		"m²"
					},
					"commercialarea": {
						"caption":	"Gewerbefläche",
						"type":		"area",
						"unit":		"m²"
					},
					"officespace": {
						"caption":	"Bürofläche",
						"type":		"area",
						"unit":		"m²"
					},
					"gastroarea": {
						"caption":	"Gastronomische Fläche",
						"type":		"area",
						"unit":		"m²"
					},
					"gastroseatingindoor": {
						"caption":	"Gastroplätze in Räumen",
						"type":		"number",
						"unit":		""
					},
					"numbersOfRooms": {
						"caption":	"Zimmer",
						"type":		"number",
						"unit":		""
					},
					"plotAreainha": {
						"caption":	"Grundstücksfläche",
						"type":		"area",
						"unit":		"ha"
					},
					"agriculturearea": {
						"caption":	"Landwirt. Fläche",
						"type":		"number",
						"unit":		"ha"
					},
					"forestryarea": {
						"caption":	"Forstwirt. Fläche",
						"type":		"number",
						"unit":		"ha"
					},
					"singlenumbersOfRooms": {
						"caption":	"Anzahl Einzelzimmer",
						"type":		"number",
						"unit":		""
					},
					"doublenumbersOfRooms": {
						"caption":	"Anzahl Doppelzimmer",
						"type":		"number",
						"unit":		""
					},
					"conferencenumbersOfRooms": {
						"caption":	"Anzahl Konferenzräume",
						"type":		"number",
						"unit":		""
					},
					"numhousingunits": {
						"caption":	"Anzahl Wohneinheiten",
						"type":		"number",
						"unit":		""
					},
					"numretailunits": {
						"caption":	"Anzahl Gewerbeeinheiten",
						"type":		"number",
						"unit":		""
					},
					"numofunits": {
						"caption":	"Anzahl Sonstige-Einheiten",
						"type":		"number",
						"unit":		""
					},
					"minpartialarea": {
						"caption":	"Minimale Teilfläche",
						"type":		"number",
						"unit":		""
					},
					"gardenarea": {
						"caption":	"Gartenfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"cellararea": {
						"caption":	"Kellerfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"yearofconstruction": {
						"caption":	"Baujahr",
						"type":		"number",
						"unit":		""
					},
					"totalFloorSpace": {
						"caption":	"Gesamtfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"usablearea": {
						"caption":	"Nutzfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"bath": {
						"caption":	"Badezimmer",
						"type":		"number",
						"unit":		""
					},
					"no_of_floors": {
						"caption":	"Etagenzahl",
						"type":		"number",
						"unit":		""
					},
					"floor": {
						"caption":	"Etage",
						"type":		"number",
						"unit":		""
					},
					"oldnewbuilding":{
						"caption":	"Alt-/Neubau",
						"type":		"option",
						"unit":		"",
						"option": {
							"0":	"Altbau",
							"1":	"Neubau"
						}
					},
					"monument": {
						"caption":	"Denkmalschutzobjekt",
						"type":		"yesno",
						"unit":		""
					},
					"typeofheating": {
						"caption":	"Heizungsart",
						"type":		"option",
						"unit":		"",
						"option": {
							"WAE":"Wärmepumpe",
							"FER":"Fernwärme",
							"FUS":"Fußbodenheizung",
							"GAS":"Gas-Heizung",
							"HOL":"Holz-Pelletheizung",
							"NAC":"Nachtspeicherofen",
							"OEL":"Öl-Heizung",
							"SOL":"Solar-Heizung",
							"01":"Etagenheizung",
							"02":"Ofenheizung",
							"03":"Zentralheizung",
							"BLO":"Blockheizkraftwerk",
							"ELE":"Elektro-Heizung"
						}
					},
					"builtin_kitchen": {
						"caption":	"Einbauküche",
						"type":		"yesno",
						"unit":		""
					},
					"guesttoilet": {
						"caption":	"Gäste-WC",
						"type":		"yesno",
						"unit":		""
					},
					"balconies": {
						"caption":	"Anzahl Balkone",
						"type":		"number",
						"unit":		""
					},
					"AnnualNetColdRentResidential": {
						"caption":	"JNKM SOLL - Wohnen",
						"type":		"currence",
						"unit":		"€"
					},
					"numbalconiesterraces": {
						"caption":	"Balkone/Terrassen",
						"type":		"number",
						"unit":		""
					},
					"terrace_surface": {
						"caption":	"Terrassenfläche",
						"type":		"area",
						"unit":		"m²"
					},
					"parking": {
						"caption":	"Stellplatztyp",
						"type":		"option",
						"unit":		"",
						"option": {
							"1":"Keine Angabe",
							"3":"Aussenstellplatz",
							"4":"Carport",
							"5":"Duplex",
							"2":"Garage",
							"6":"Parkhaus",
							"7":"Tiefgarage"
						}
					},
					"carportnum": {
						"caption":	"Stellplatzanzahl",
						"type":		"number",
						"unit":		""
					},
					"carportpurchaseprice": {
						"caption":	"Stellplatzkaufpreis",
						"type":		"currence",
						"unit":		"€"
					},
					"garagepurchaseprice": {
						"caption":	"Garagenkaufpreis",
						"type":		"currence",
						"unit":		"€"
					},
					"numgarages": {
						"caption":	"Garagenanzahl",
						"type":		"number",
						"unit":		""
					},
					"availableat": {
						"caption":	"Verfügbar ab",
						"type":		"date",
						"unit":		""
					},
					"securitydeposit": {
						"caption":	"Kaution",
						"type":		"text",
						"unit":		""
					},
					"balconies": {
						"caption":	"Anzahl Balkone",
						"type":		"number",
						"unit":		""
					},
					"petsallowed": {
						"caption":	"Haustiere erlaubt",
						"type":		"yesno",
						"unit":		""
					},
					"sharedflatsuitable": {
						"caption":	"WG geeignet",
						"type":		"yesno",
						"unit":		""
					},
					"garagerent": {
						"caption":	"Garagenmiete",
						"type":		"currence",
						"unit":		"€"
					},
					"carportrent": {
						"caption":	"Stellplatzmiete",
						"type":		"currence",
						"unit":		"€"
					},
					"let": {
						"caption":	"Vermietet",
						"type":		"yesno",
						"unit":		""
					},
					"xtnsn_immobilien_verkauf_mieteinnahmen_pro_monat": {
						"caption":	"Mieteinnahmen pro Monat",
						"type":		"number",
						"unit":		""
					},
					"elevator_general": {
						"caption":	"Aufzug",
						"type":		"yesno",
						"unit":		""
					},
					"completiondate": {
						"caption":	"Bezugstermin",
						"type":		"text",
						"unit":		""
					},
					"constructibleaccto": {
						"caption":	"Bebaubar nach",
						"type":		"option",
						"unit":		"",
						"option": {
							"1":"Aussengebiet",
							"2":"Nachbarbebauung",
							"3":"Bebauungsplan",
							"4":"Bauerwartungsland",
							"5":"Kein Bauland",
							"1":"Aussengebiet",
							"2":"Nachbarbebauung",
							"3":"Bebauungsplan"
						}
					},
					"buildingpermit": {
						"caption":	"Baugenehmigung vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					"demolition": {
						"caption":	"Abriß von Altlasten",
						"type":		"yesno",
						"unit":		""
					},
					"brownfieldsite": {
						"caption":	"Altlasten",
						"type":		"text",
						"unit":		""
					},
					"development": {
						"caption":	"Erschließung",
						"type":		"option",
						"unit":		"",
						"option": {
							"TE":"Teilweise erschlossen",
							"VE":"Voll erschlossen",
							"NE":"Nicht erschlossen"
						}
					},
					"infrastructurecosts": {
						"caption":	"Erschließungskosten",
						"type":		"currence",
						"unit":		"€"
					},
					"hereditarylease": {
						"caption":	"Erbpacht",
						"type":		"text",
						"unit":		"pro Monat"
					},
					"groundrent": {
						"caption":	"Erbbauzins",
						"type":		"number",
						"unit":		""
					},
					"local_subdistrict": {
						"caption":	"Gemarktung",
						"type":		"text",
						"unit":		""
					},
					"buildingplot": {
						"caption":	"Kurzfristig bebaubar",
						"type":		"yesno",
						"unit":		""
					},
					"qualsurroundings": {
						"caption":	"Qualität des Umfelds",
						"type":		"option",
						"unit":		"",
						"option": {
							"5":"mangelhaft",
							"1":"sehr gut",
							"2":"gut",
							"3":"befriedigend",
							"6":"ungenügend",
							"4":"ausreichend"
						}
					},
					"traveltimemainstation": {
						"caption":	"Fahrzeit Hauptbahnhof",
						"type":		"number",
						"unit":		"min"
					},
					"traveltimebab": {
						"caption":	"Fahrzeit nächste Autobahnauffahrt",
						"type":		"number",
						"unit":		"min"
					},
					"traveltimeairport": {
						"caption":	"Fahrzeit nächster Flughafen",
						"type":		"number",
						"unit":		"min"
					},
					"payloadelevator": {
						"caption":	"Tragkraft des Personenaufzug",
						"type":		"number",
						"unit":		"kg"
					},
					"withrestaurant": {
						"caption":	"Angeschlossene Gastronomie",
						"type":		"option",
						"unit":		"",
						"option": {
							"2":"Bar",
							"1":"Hotelrestaurant"
						}
					},
					"flooring": {
						"caption":	"Bodenbelag",
						"type":		"option",
						"unit":		"",
						"option": {
							"flooring_deal":"Dielen",
							"flooring_epoxy":"Epoxidharzboden",
							"flooring_carpet":"Teppichboden",
							"flooring_cement":"Beton",
							"flooring_antistaticcarpet":"Antistatischer Teppichboden",
							"flooring_doublefloor":"Doppelboden",
							"flooring_tile":"Fliesen",
							"flooring_leaserwish":"Nach Mieterwunsch",
							"flooring_laminate":"Laminat",
							"flooring_stone":"Stein",
							"flooring_linoleum":"Ohne Bodenbelag",
							"flooring_pvc":"PVC",
							"flooring_chairrolesacceptingcarpettiles":"Stuhlrollenfeste Teppichfliesen",
							"flooring_parquet":"Parkett",
							"flooring_marble":"Marmor",
							"flooring_terracotta":"Terrakotta",
							"flooring_granite":"Granit",
							"10":"Dielen",
							"02":"Epoxidharzboden",
							"05":"Teppichboden",
							"01":"Beton",
							"051":"Antistatischer Teppichboden",
							"11":"Doppelboden",
							"03":"Fliesen",
							"08":"Nach Mieterwunsch",
							"06":"Laminat",
							"011":"Stein",
							"09":"Ohne Bodenbelag",
							"07":"PVC",
							"052":"Stuhlrollenfeste Teppichfliesen",
							"04":"Parkett",
							"marble":"Marmor",
							"terracotta":"Terrakotta",
							"granit":"Granit",
							"vinyl":"Vinyl"
						}
					},
					"bathroomproperties": {
						"caption":	"Ausstattung des Bades",
						"type":		"option",
						"unit":		"",
						"option": {
							"bathprop_window":"Fenster",
							"bathprop_pissoir":"Pissoir",
							"bathprop_shower":"Dusche",
							"bathprop_bidet":"Bidet",
							"bathprop_bathtub":"Badewanne",
							"window":"Fenster",
							"pissoir":"Pissoir",
							"shower":"Dusche",
							"bidet":"Bidet",
							"bathtub":"Badewanne"
						}
					},
					"condition": {
						"caption":	"Zustand",
						"type":		"option",
						"unit":		"",
						"option": {
							"10":"projektiert",
							"01":"Erstbezug",
							"03":"Neuwertig",
							"06":"Vollständig renoviert",
							"08":"Renovierungsbedürftig",
							"05":"Modernisiert",
							"09":"Nach Vereinbarung",
							"02":"Erstbezug nach Sanierung",
							"04":"Saniert",
							"07":"Gepflegt",
							"11":"Unsaniert",
							"031":"modernisiert",
							"032":"Erstbezug nach Sanierung",
							"033":"saniert",
							"021":"gepflegt"
						}
					},
					"identifier": {
						"caption":	"Immobilien-ID",
						"type":		"text",
						"unit":		""
					},	
					"commissioninclvat": {
						"caption":	"Provision inkl. MWST",
					  "type":		"yesno",
						"unit":		""
					},
					"commissionProspect": {
						"caption":	"Provision",
						"type":		"text",
						"unit":		""
					}
				},
				"finance":{
					"purchaseprice": {
						"caption":	"Kaufpreis",
						"type":		"number",
						"unit":		"€"
					}
				},	
				"equipments":{
					"cellar": {
						"caption":	"Keller",
						"type":		"yesno",
						"unit":		""
					},
					"furnished":{
						"caption":	"Möbliert",
						"type":		"yesno",
						"unit":		""
					},
					"lodger_flat": {
						"caption":	"Einliegerwohnung vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					" barrierFree": {
						"caption":	"Barrierefrei",
						"type":		"yesno",
						"unit":		""
					},
					"wheelchairaccess": {
						"caption":	"Rollstuhlgerecht",
						"type":		"yesno",
						"unit":		""
					},
					"elevator": {
						"caption":	"Aufzug",
						"type":		"yesno",
						"unit":		""
					},
					"ramp": {
						"caption":	"laderampe",
						"type":		"yesno",
						"unit":		""
					},
					"canteencafeteria": {
						"caption":	"Kantine/Cafeteria",
						"type":		"yesno",
						"unit":		""
					},
					"guestterrace": {
						"caption":	"Gastterrasse",
						"type":		"yesno",
						"unit":		""
					},
					"assisted_living": {
						"caption":	"Seniorengerecht",
						"type":		"yesno",
						"unit":		""
					},
					"let": {
						"caption":	"Vermietet",
						"type":		"yesno",
						"unit":		""
					},
					"guesttoilet": {
						"caption":	"Gäste-WC",
						"type":		"yesno",
						"unit":		""
					},
					"balconyavailable": {
						"caption":	"Balkon vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					"terraceavailable": {
						"caption":	"Terrasse vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					"sauna": {
						"caption":	"Sauna vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					"swimmingpool": {
						"caption":	"Swimmingpool vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					"wintergarden": {
						"caption":	"Wintergarten vorhanden",
						"type":		"yesno",
						"unit":		""
					},
					"builtin_kitchen": {
						"caption":	"Einbauküche",
						"type":		"yesno",
						"unit":		""
					},
					"dpwiring": {
						"caption":	"DV Verkabelung",
						"type":		"yesno",
						"unit":		""
					},
					"shutters": {
						"caption":	"Rollladen vorhanden",
						"type":		"yesno",
						"unit":		""
					}
				},
				"energyUsage":{
					"energyIdentificationType": {
						"caption":	"Enerigeausweistyp",
						"type":		"option",
						"unit":		"",
						"option": {
							"3":"Verbrauchsausweis",
							"2":"Bedarfsausweis"
						}
					},
					"energyidentificationtype": {
						"caption":	"Enerigeausweistyp",
						"type":		"option",
						"unit":		"",
						"option": {
							"3":"Verbrauchsausweis",
							"2":"Bedarfsausweis"
						}
					},
					"energy_required": {
						"caption":	"Endenergiebedarf",
						"type":		"number",
						"unit":		"KWh(m²*a)"
					},
					"energyUsageValue": {
						"caption":	"Energiekennwert",
						"type":		"number_formatted",
						"unit":		"KWh(m²*a)"
					},
					"energyusagevalue": {
						"caption":	"Energiekennwert",
						"type":		"number_formatted",
						"unit":		"KWh(m²*a)"
					},
					"energyEfficienceClass": {
						"caption":	"Energieeffizienzklasse",
						"type":		"option",
						"unit":		"",
						"option": {
							"01":"A+",
							"02":"A",
							"03":"B",
							"04":"C",
							"05":"D",
							"06":"E",
							"07":"F",
							"08":"G",
							"09":"H"
						}
					},
					"energyefficienceclass": {
						"caption":	"Energieeffizienzklasse",
						"type":		"option",
						"unit":		"",
						"option": {
							"01":"A+",
							"02":"A",
							"03":"B",
							"04":"C",
							"05":"D",
							"06":"E",
							"07":"F",
							"08":"G",
							"09":"H"
						}
					},
					"energyWithWarmWater": {
						"caption":	"Energie mit Warmwasser",
						"type":		"yesno",
						"unit":		""
					},
					"energywithwarmwater": {
						"caption":	"Energie mit Warmwasser",
						"type":		"yesno",
						"unit":		""
					},
					"energidentificationdate": {
						"caption":	"Energieausweis erstellt am",
						"type":		"date",
						"unit":		""
					},
					"pass_valid_till": {
						"caption":	"Energieausweis gültig bis",
						"type":		"date",
						"unit":		""
					},
					"typeofheating": {
						"caption":	"Heizungsart",
						"type":		"option",
						"unit":		"",
						"option": {
							"WAE":"Wärmepumpe",
							"FER":"Fernwärme",
							"FUS":"Fußbodenheizung",
							"GAS":"Gas-Heizung",
							"HOL":"Holz-Pelletheizung",
							"NAC":"Nachtspeicherofen",
							"OEL":"Öl-Heizung",
							"SOL":"Solar-Heizung",
							"01":"Etagenheizung",
							"02":"Ofenheizung",
							"03":"Zentralheizung",
							"BLO":"Blockheizkraftwerk",
							"ELE":"Elektro-Heizung"
						}
					},
					"fuelenergy_type": {
						"caption":	"Befeuerung / Energieträger",
						"type":		"option",
						"unit":		"",
						"option": {
							"19":"Nahwärme",
							"20":"Wärmepumpe",
							"21":"Wärmelieferung",
							"5":"Gas",
							"1":"Keine Angabe",
							"6":"Öl",
							"11":"Erdgas leicht",
							"12":"Erdgas schwer",
							"13":"Flüssiggas",
							"14":"Fernwärme Dampf",
							"2":"Erdwärme",
							"7":"Fernwärme",
							"9":"Kohle",
							"4":"Pelletheizung",
							"3":"Solarheizung",
							"8":"Strom",
							"16":"Holz",
							"17":"Holz-Hackschnitzel",
							"18":"Kohle/Koks",
							"ER1":"Erdgas leicht",
							"ER2":"Erdgas schwer",
							"FLU":"Flüssiggas",
							"FER":"Fernwärme Dampf",
							"HO1":"Holz",
							"HO2":"Holz-Hackschnitzel",
							"KOH":"Kohle/Koks",
							"NAH":"Nahwärme",
							"WAE":"Wärmelieferung",
							"BI1":"Bioenergie",
							"fe":"Fernwärme",
							"ga":"Gas",
							"zz":"Keine Angabe",
							"ko":"Kohle",
							"ol":"Öl",
							"so":"Solar",
							"st":"Strom",
							"er":"Erdwärme",
							"pe":"Pellet",
							"wa":"Wärmepumpe"
						}
					}
				},
				"estatetype":{
					"estatetype": {
						"caption":	"Immobilienart",
						"type":		"option",
						"unit":		"",
						"option":	{
							"15EM":"Ein/Mehrfamilienhaus (ZV)",
							"16EM":"EinfamilienhausMitEinliegerwohnung (Typ)",
							"15GE":"Gewerbe/Anlage (ZV)",
							"16HO":"Holzhaus (Typ)",
							"14LO":"Loft (WG)",
							"14TE":"Terrassenwohnung (WG)",
							"16":"Typenhäuser (Typ)",
							"02REND":"Reihenendhaus",
							"02ZSTAD":"Stadthaus",
							"02ZREST":"Resthof",
							"02ZLAND":"Landhaus",
							"02ZBERG":"Berghütte",
							"02ZCHAL":"Chalet",
							"02ZSTRA":"Strandhaus",
							"02ZLAUB":"Laube/Datsche/Gartenhaus",
							"02ZAPAH":"Apartmenthaus",
							"02ZHERR":"Herrenhaus",
							"02ZFINC":"Finca",
							"02ZRUST":"Rustico",
							"02ZFERT":"Fertighaus",
							"03INDU":"Baugrund für Industrie",
							"03GEMI":"Gemischte Nutzung",
							"03GEWE":"Gewerbepark",
							"03SOND":"Sondernutzung",
							"03SEEL":"Seeliegenschaft",
							"05EINHA":"Einzelhandelsladen",
							"05VERBR":"Verbrauchermarkt",
							"01ZAPART":"Apartment",
							"01ZFERIE":"Ferienwohnung",
							"01ZGALER":"Galerie",
							"08GASTW":"Gastronomie mit Wohnung",
							"08BEHERB":"Weitere Beherbergungsbetriebe",
							"08RAUCH":"Raucherlokal",
							"08EINRA":"Einraumlokal",
							"07PROD":"Produktion",
							"07FREIF":"Freiflächen",
							"09AUSS":"Aussiedlerhof",
							"09GART":"Gartenbau",
							"09ACKE":"Ackerbau",
							"09VIEH":"Viehwirtschaft",
							"09JAGD":"Jagd- u. Forstwirtschaft",
							"09TEICH":"Teich- u. Fischwirtschaft",
							"09SCHEU":"Scheunen",
							"09SONST":"Sonstige Landwirtschaftsimmobilien",
							"09JAGDR":"Jagdrevier",
							"11DOPP":"Doppelgarage",
							"11BOOT":"Bootsliegeplatz",
							"11EINZE":"Einzelgarage",
							"11STROM":"Parkplatz-Strom",
							"04VERB":"Verbrauchermärkte (Invest)",
							"04PFLEG":"Pflegeheim (Invest)",
							"04SANAT":"Sanatorium (Invest)",
							"04SENIO":"Seniorenheim (Invest)",
							"04CBETRE":"Betreutes Wohnen (Invest)",
							"20":"Freizeitimmobilien gewerblich",
							"20SPORT":"Sportanlagen",
							"20VERGN":"Vergnügungspark/-Center",
							"21":"Sonstige Typen",
							"21PARKH":"Parkhaus",
							"21TANKS":"Tankstelle",
							"21KRANK":"Krankenhaus",
							"21SONST":"Sonstige",
							"15GR":"Grundstück (ZV)",
							"02SON":"sonstige Häuser",
							"01LOFT":"Loftwohnung",
							"02MFH":"Mehrfamilienhaus",
							"08HOTG":"Hotel garni",
							"01ETAG":"Etagenwohnung",
							"02DZH":"Zweifamilienhaus",
							"07LKÜ":"Kühlhaus",
							"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR":"Kühlregallager",
							"08GAHS":"Gästehaus",
							"07LFR":"Lager mit Freifläche",
							"07L":"Lagerfläche",
							"01ZO":"sonstiger Wohnungstyp",
							"08":"Gastronomie / Beherbergungen",
							"06A1":"Loft",
							"06":"Büro / Praxis / Ausstellungsräume",
							"04W03":"Mehrfamilienhaus (Invest.)",
							"07LH":"Lagerhalle",
							"04":"Anlage-/Investmentobjekte",
							"07SF":"Servicefläche",
							"07LSP":"Speditionslager",
							"07W":"Werkstatt",
							"02ZB":"besondere Immobilie",
							"09R":"Reiterhof",
							"01MAIS":"Maisonettewohnung",
							"03GL":"Grundstück Land und Forstwirtschaft",
							"03":"Grundstücke",
							"10GE":"Gewerbeeinheit",
							"10S":"Spezialobjekt",
							"02LBH":"Bauernhaus",
							"03GG":"Baugrund für Gewerbe",
							"08HOT":"Hotel",
							"06A":"Atelier",
							"09":"Land- / Forstwirtschaft",
							"02":"Haus",
							"04W04":"Wohnanlage (Invest.)",
							"07":"Prod./ Lager / Gewerbehallen",
							"08GAE":"Gaststätte",
							"04W02":"Einfamilienhaus (Invest.)",
							"01PENT":"Penthouse",
							"02EFH":"Einfamilienhaus",
							"04W01":"Eigentumswohnung (Invest.)",
							"02REH":"Reihenhaus",
							"04EZ":"Einkaufszentrum (Invest.)",
							"03GF":"Baugrund für Freizeit",
							"02VIL":"Villa",
							"04GA":"Gaststätte (Invest.)",
							"06B":"Büro",
							"04K":"Freizeitanlage (Invest.)",
							"08REST":"Restaurant",
							"01":"Wohnung",
							"08PENS":"Pension",
							"01DACH":"Dachgeschosswohnung",
							"04W05":"Wohn-/Geschäftshaus (Invest.)",
							"05":"Läden/SB-Märkte",
							"02DHH":"Doppelhaushälfte",
							"06BE":"Büroetage",
							"10":"Sonstige Immobilie",
							"07H":"Halle",
							"01TERR":"Terrassenwohnung",
							"01GERD":"Erdgeschosswohnung",
							"06PH":"Praxishaus",
							"06G":"Gewerbezentrum",
							"05F":"Verkaufshalle",
							"08B":"Bar",
							"07LHO":"Hochregallager",
							"07HI":"Industriehalle",
							"07HIF":"Industriehalle mit Freifläche",
							"10F":"Freizeitanlage",
							"10G":"Gewerbefläche",
							"06BH":"Bürohaus",
							"06BG":"Bürozentrum",
							"06BL":"Büro & Lagergebäude",
							"06P":"Praxis",
							"06PE":"Praxisetage",
							"05A":"Ausstellungsfläche",
							"05E1":"Einkaufszentrum",
							"05E2":"Kaufhaus",
							"05K":"Kiosk",
							"05L":"Laden",
							"11C":"Carport",
							"02REHM":"Reihenmittelhaus",
							"10W":"Werkstatt (Produktion)",
							"14DA":"Dachgeschoss (WG)",
							"16FA":"Fachwerkhaus (Typ)",
							"14MA":"Maisonette (WG)",
							"14PE":"Penthouse (WG)",
							"16DO":"Doppelhaus (Typ)",
							"15GA":"Garage/Sonstige (ZV)",
							"14SU":"Souterrain (WG)",
							"01ZROHD":"Rohdachboden (AUT)",
							"01ZATTIK":"Attikawohnung",
							"05E":"SB-Markt",
							"05LV":"Verkaufsfläche",
							"08C":"Cafe",
							"08D":"Diskothek",
							"08HOTA":"Hotelanwesen",
							"09A1":"Anwesen",
							"09A2":"Bauernhof",
							"09W":"Weingut",
							"04GWE":"Gewerbeeinheit (Invest.)",
							"04EG":"Geschäftshaus (Invest.)",
							"04GH":"Halle/Lager (Invest.)",
							"04E":"Laden/Verkaufsfläche (Invest.)",
							"04ES":"Supermarkt (Invest.)",
							"04B":"Bürogebäude (Invest.)",
							"04GWA":"Gewerbeanwesen (Invest.)",
							"04S":"Servicecenter (Invest.)",
							"04Z":"Sonstiges (Invest.)",
							"04GAH":"Hotel (Invest.)",
							"04GWI":"Industrieanwesen (Invest.)",
							"15EI":"Eigentumswohnung (ZV)",
							"16EI":"Einfamilienhaus (Typ)",
							"16LA":"Landhaus (Typ)",
							"14SO":"Sonstige (WG)",
							"16SV":"Stadtvilla (Typ)",
							"14":"WG-Zimmer (WG)",
							"15":"Zwangsversteigerung (ZV)",
							"16ZW":"Zweifamilienhaus (Typ)",
							"12A":"Appartement",
							"08F":"Ferienbungalows",
							"02EFE":"Einfamilienhaus mit Einliegerwohnung",
							"11G":"Garage",
							"11T":"Tiefgaragenstellplatz",
							"10GP":"Gewerbepark",
							"12H":"Haus",
							"12W":"Wohnung (WAZ)",
							"12Z":"Zimmer (WAZ)",
							"12":"Wohnen auf Zeit (WAZ)",
							"16BL":"Blockhaus (Typ)",
							"11S":"Stellplatz",
							"07A":"Ausstellungsfläche (Produktion)",
							"02BNG":"Bungalow",
							"02BURG":"Burg/Schloss",
							"06BUGE":"Büro- u. Geschäftsgebäude",
							"11D":"Duplex",
							"11":"Garage Stellplatz",
							"01HP":"Hochparterre",
							"11P":"Parkhausstellplatz",
							"02REHE":"Reiheneckhaus",
							"01SOUT":"Souterrain",
							"06WOGE":"Wohn- u. Geschäftsgebäude",
							"14ER":"Erdgeschoss (WG)",
							"08Beher":"Beherbergungsbetrieb",
							"03indust":"Baugrundstück für Wohnungen und Industrie",
							"03dup":"Baugrundstück für freistehende und Duplexhäuser",
							"03BM":"Baugrund für Mehrfamilienhäuser",
							"03BWG":"Baugrund für Wohnen und Gewerbe",
							"03GS":"Grundstück für Soziales",
							"04GW":"Industrie- und Gewerbeimmobilien (Invest.)",
							"04HI":"Handelsimmobilien (Invest.)",
							"04HIF":"Fachmarktzentrum (Invest.)",
							"04HIK":"Kaufhaus (Invest.)",
							"04SI":"Sozialimmobilien (Invest.)",
							"04SIB":"Betreutes Wohnen (Invest.)",
							"04SIP":"Pflegeheim (Invest.)",
							"04SIK":"Klinik (Invest.)",
							"04W":"Wohnimmobilien (Invest.)",
							"04ZP":"Parkhaus (Invest.)",
							"09F":"Fischzucht",
							"08PENT":"Boardinghaus",
							"11Z":"Sonstiges",
							"01LOFT":"Loftwohnung",
							"08HOTG":"Hotel garni",
							"01ETAG":"Etagenwohnung",
							"02DZH":"Zweifamilienhaus",
							"07LKÜ":"Kühlhaus",
							"03BE":"Baugrund für Ein- / Zweifamilienhäuser",
							"07LKÜR":"Kühlregallager",
							"08GAHS":"Gästehaus",
							"07LFR":"Lager mit Freifläche",
							"07L":"Lagerfläche",
							"01ZO":"Sonstiger Wohnungstyp",
							"08":"Hotellerie- und Gastronomieflächen",
							"06A1":"Loft",
							"06":"Gewerbeflächen",
							"04W03":"Mehrfamilienhaus (Invest.)",
							"07LH":"Lagerhalle",
							"04":"Anlage-/Investmentobjekte",
							"07SF":"Servicefläche",
							"07LSP":"Speditionslager",
							"07W":"Werkstattsfläche",
							"02ZB":"Besondere Immobilie",
							"09R":"Reiterhof",
							"01MAIS":"Maisonettewohnung",
							"03GL":"Grundstück Land und Forstwirtschaft",
							"03":"Grundstücke",
							"10GE":"Gewerbeeinheit",
							"10S":"Spezialobjekt",
							"02LBH":"Bauernhaus",
							"03GG":"Baugrund für Gewerbe",
							"08HOT":"Hotel",
							"06A":"Atelier",
							"09":"Land- / Forstwirtschaft",
							"02":"Haus",
							"04W04":"Wohnanlage (Invest.)",
							"07":"Produktions- und Lagerflächen",
							"08GAE":"Gaststätte",
							"04W02":"Einfamilienhaus (Invest.)",
							"01PENT":"Penthouse",
							"02EFH":"Einfamilienhaus",
							"04W01":"Eigentumswohnung (Invest.)",
							"02REH":"Reihenhaus",
							"04HIE":"Einkaufszentrum (Invest.)",
							"03GF":"Baugrund für Freizeit",
							"02MFH":"Mehrfamilienhaus",
							"02EFE":"Einfamilienhaus mit Einliegerwohnung",
							"11G":"Garage",
							"11T":"Tiefgaragenstellplatz",
							"11S":"Stellplatz",
							"12A":"Apartment",
							"08F":"Ferienimmobilie",
							"10GP":"Gewerbepark",
							"12H":"Haus",
							"12W":"Wohnung",
							"12Z":"Zimmer",
							"07A":"Ausstellungsfläche (Produktion)",
							"02BNG":"Bungalow",
							"06BUGE":"Büro- und Geschäftsgebäude",
							"11C":"Carport",
							"11D":"Duplex",
							"11":"Garage Stellplatz",
							"01HP":"Hochparterre",
							"11P":"Parkhausstellplatz",
							"02REHM":"Reihenmittelhaus",
							"01SOUT":"Souterrain",
							"06WOGE":"Wohn- und Geschäftsgebäude",
							"02REHE":"Reiheneckhaus",
							"10W":"Werkstatt (Produktion)",
							"02VIL":"Villa",
							"04GA":"Gaststätte / Gasthaus (Invest.)",
							"06B":"Bürofläche",
							"04ZF":"Freizeitimmobilie (Invest.)",
							"08REST":"Restaurant",
							"01":"Wohnung",
							"08PENS":"Pension",
							"01DACH":"Dachgeschosswohnung",
							"04W05":"Wohn-/Geschäftshaus (Invest.)",
							"05":"Einzelhandelsflächen",
							"02DHH":"Doppelhaushälfte",
							"06BE":"Büroetage",
							"10":"Sonstige Objekte",
							"07H":"Halle",
							"01TERR":"Terrassenwohnung",
							"01GERD":"Erdgeschosswohnung",
							"06PH":"Praxishaus",
							"06G":"Gewerbezentrum",
							"05F":"Verkaufshalle",
							"08B":"Bar",
							"07LHO":"Hochregallager",
							"07HI":"Produktionsfläche",
							"07HIF":"Industriehalle mit Freifläche",
							"10F":"Freizeitanlage",
							"10G":"Gewerbefläche",
							"06BH":"Bürohaus",
							"06BG":"Bürozentrum",
							"06BL":"Büro und Lagergebäude",
							"06P":"Praxis",
							"06PE":"Praxisfläche",
							"05A":"Ausstellungsfläche",
							"05E1":"Einkaufszentrum",
							"05F1":"Factory Outlet",
							"05E2":"Kaufhaus",
							"05K":"Kiosk",
							"05L":"Laden",
							"05E":"SB-Markt",
							"05LV":"Verkaufsfläche",
							"08C":"Cafe",
							"08D":"Diskothek",
							"08HOTA":"Hotelanwesen",
							"09A1":"Anwesen",
							"09A2":"Bauernhof",
							"09W":"Weingut",
							"04GWE":"Gewerbeeinheit (Invest.)",
							"04GWG":"Geschäftshaus, Handel, Büro (Invest.)",
							"04GWH":"Halle/Lager (Invest.)",
							"04HIL":"Laden/Verkaufsfläche (Invest.)",
							"04HIS":"Supermarkt (Invest.)",
							"04GWB":"Bürogebäude (Invest.)",
							"04GWA":"Gewerbeanwesen (Invest.)",
							"04GWS":"Servicecenter (Invest.)",
							"04Z":"Sonstiges (Invest.)",
							"04GAH":"Hotel (Invest.)",
							"04GWI":"Industrieanwesen (Invest.)",
							"02BURG":"Burg/Schloss",
							"02SON":"Sonstige Häuser",
							"12":"Wohnen auf Zeit"
						}
					}
				},
				"geo":{
					"longitude":{
						"caption":	"longitude",
						"type":		"text",
						"unit":		""
					},
					"latitude":{
						"caption":	"latitude",
						"type":		"text",
						"unit":		""
					}
				}
			}				
		}
	}';
	define('FF_ESTATEVIEW_SALESAUTOMATE_MAPPING', $mapping);
	define('FF_ESTATEVIEW_SALESAUTOMATE_PUBLISH_FLAG', 'web_display' );







